# Exploring the data downloaded from USDA FoodData Central

See the download here: https://fdc.nal.usda.gov/download-datasets.html

Data available in `.data/`.

Data dictionary available in  `nutrify/data_exploration/data/FoodData_Central_foundation_food_csv_2021-04-28/Download & API Field Descriptions April 2021.pdf`

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Get Data

In [236]:
# Import databases
food = pd.read_csv("data/FoodData_Central_foundation_food_csv_2026-04-30/food.csv")
food_survey = pd.read_csv("data/FoodData_Central_survey_food_csv_2024-10-31/food.csv")
nutrient = pd.read_csv("data/FoodData_Central_Supporting_Data_csv_2022-10-28/nutrient.csv")
food_nutrient = pd.read_csv("data/FoodData_Central_foundation_food_csv_2026-04-30/food_nutrient.csv")
food_nutrient_survey = pd.read_csv("data/FoodData_Central_survey_food_csv_2024-10-31/food_nutrient.csv")

print(len(food), len(food_survey), len(nutrient), len(food_nutrient), len(food_nutrient_survey))

# Combine food and food_survey and drop columns that don't have a description 
food = pd.concat([food, food_survey], ignore_index=True)
food = food.dropna(subset=["description"])
food["description"] = food["description"].str.lower()
print(f"Combined food rows: {len(food)}")

# Combine food_nutrient and food_nutrient_survey
food_nutrient = pd.concat(
    [food_nutrient, food_nutrient_survey],
    ignore_index=True
)
food_nutrient["nutrient_name"] = food_nutrient["nutrient_id"].map(nutrient.set_index("id")["name"]).str.lower() 
print(f"Combined food nutrient rows: {len(food_nutrient)}")

C:\Users\pyaes\AppData\Local\Temp\ipykernel_7300\2043736291.py:5: DtypeWarning: Columns (0: footnote) have mixed types. Specify dtype option on import or set low_memory=False.
  food_nutrient = pd.read_csv("data/FoodData_Central_foundation_food_csv_2026-04-30/food_nutrient.csv")

87990 5432 474 170469 353015
Combined food rows: 93414
Combined food nutrient rows: 523484

In [3]:
nutrient[nutrient["name"].str.contains("Energy")]

      id                               name unit_name  nutrient_nbr   rank
0   2047   Energy (Atwater General Factors)      KCAL         957.0  280.0
1   2048  Energy (Atwater Specific Factors)      KCAL         958.0  290.0
9   1008                             Energy      KCAL         208.0  300.0
63  1062                             Energy        kJ         268.0  400.0

In [4]:
food_nutrient.columns

Index(['id', 'fdc_id', 'nutrient_id', 'amount', 'data_points', 'derivation_id',
       'min', 'max', 'median', 'footnote', 'min_year_acquired',
       'nutrient_name'],
      dtype='str')

In [5]:
len(food_nutrient)

523484

In [6]:
food.head()

,fdc_id,data_type,description,food_category_id,publication_date
0,319874,sample_food,"hummus, sabra classic",16.0,2019-04-01
1,319875,market_acquisition,"hummus, sabra classic",16.0,2019-04-01
2,319876,market_acquisition,"hummus, sabra classic",16.0,2019-04-01
3,319877,sub_sample_food,hummus,16.0,2019-04-01
4,319878,sub_sample_food,hummus,16.0,2019-04-01

In [7]:
food_nutrient.head()

,id,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acquired,nutrient_name
0,2201847,319877,1051,56.30,1.0,1.0,NaN,NaN,NaN,NaN,NaN,water
1,2201845,319877,1002,1.28,1.0,1.0,NaN,NaN,NaN,NaN,NaN,nitrogen
2,2201846,319877,1004,19.00,1.0,1.0,NaN,NaN,NaN,NaN,NaN,total lipid (fat)
3,2201844,319877,1007,1.98,1.0,1.0,NaN,NaN,NaN,NaN,NaN,ash
4,2201852,319878,1091,188.00,1.0,1.0,NaN,NaN,NaN,NaN,NaN,"phosphorus, p"

In [8]:
# How many unique?
unique_descriptions = food["description"].unique()
len(unique_descriptions)

17130

Beautiful, this gives us ~11368 foods to work with as a goal to model. But surely they can be split into less categories?

In [9]:
unique_descriptions[:10]

<ArrowStringArray>
['hummus, sabra classic',                'hummus',         'hummus, other',
    'hummus - nfy12140o',    'hummus - nfy12140p',    'hummus - nfy12140q',
    'hummus - nfy12140r',    'hummus - nfy12140s',    'hummus - nfy12140f',
    'hummus - nfy12140g']
Length: 10, dtype: str

Where do these descriptions come from?

How can we reduce them down to like 10 unique foods and keep it simple...

In [10]:
unique_descriptions[-10:]

<ArrowStringArray>
[                'celery, cooked, as ingredient',
 'dark green vegetables as ingredient in omelet',
              'tomatoes as ingredient in omelet',
      'other vegetables as ingredient in omelet',
               'mirepoix, cooked, as ingredient',
             'vegetables as ingredient in curry',
             'vegetables as ingredient in soups',
             'vegetables as ingredient in stews',
             'sauce as ingredient in hamburgers',
          'industrial oil as ingredient in food']
Length: 10, dtype: str

In [11]:
# Find random indexes of food to explore
import random
random_number = random.randint(0, len(unique_descriptions)-10)
unique_descriptions[random_number:random_number+10]

<ArrowStringArray>
['sauce, pasta, hunts original, canned spaghetti sauce, 26.5 oz container (ca1) - nfy0905jx',
 'sauce, pasta, hunts original, canned spaghetti sauce, 26.5 oz container (ca1) - nfy0905jy',
          'minerals, sauce, pasta, hunts original, canned spaghetti sauce (ca1) - nfy0904z1',
        'proximates, sauce, pasta, hunts original, canned spaghetti sauce (ca1) - nfy0904z3',
                      'sauce, pasta, hunts original, canned spaghetti sauce (nc1) - cy0908j',
 'sauce, pasta, hunts original, canned spaghetti sauce, 26.5 oz container (nc1) - nfy0905kc',
 'sauce, pasta, hunts original, canned spaghetti sauce, 26.5 oz container (nc1) - nfy0905kb',
          'minerals, sauce, pasta, hunts original, canned spaghetti sauce (nc1) - nfy0904zd',
        'proximates, sauce, pasta, hunts original, canned spaghetti sauce (nc1) - nfy0904zf',
                      'sauce, pasta, hunts original, canned spaghetti sauce (ny1) - cy0908f']
Length: 10, dtype: str

### Food Categories

Let's dive into food categories.

In [12]:
food.head()

,fdc_id,data_type,description,food_category_id,publication_date
0,319874,sample_food,"hummus, sabra classic",16.0,2019-04-01
1,319875,market_acquisition,"hummus, sabra classic",16.0,2019-04-01
2,319876,market_acquisition,"hummus, sabra classic",16.0,2019-04-01
3,319877,sub_sample_food,hummus,16.0,2019-04-01
4,319878,sub_sample_food,hummus,16.0,2019-04-01

In [13]:
unique_categories = food["food_category_id"].unique()
unique_categories

array([1.600e+01, 1.000e+00, 1.300e+01, 1.100e+01, 2.000e+00, 7.000e+00,
       1.200e+01, 6.000e+00, 9.000e+00, 1.800e+01, 4.000e+00, 5.000e+00,
       1.500e+01, 1.900e+01, 2.500e+01, 1.000e+01,       nan, 2.000e+01,
       1.400e+01, 1.700e+01, 9.602e+03, 1.004e+03, 1.002e+03, 1.006e+03,
       1.008e+03, 1.202e+03, 1.902e+03, 1.820e+03, 1.822e+03, 8.412e+03,
       5.802e+03, 9.007e+03, 9.010e+03, 1.206e+03, 1.204e+03, 1.208e+03,
       1.402e+03, 7.220e+03, 9.404e+03, 9.402e+03, 9.999e+03, 8.008e+03,
       8.006e+03, 5.804e+03, 5.502e+03, 1.602e+03, 1.604e+03, 3.602e+03,
       2.502e+03, 3.720e+03, 6.432e+03, 2.002e+03, 2.004e+03, 9.008e+03,
       2.602e+03, 2.604e+03, 2.006e+03, 3.002e+03, 8.002e+03, 2.008e+03,
       2.206e+03, 2.202e+03, 2.204e+03, 2.010e+03, 2.606e+03, 2.608e+03,
       2.402e+03, 2.404e+03, 3.404e+03, 3.004e+03, 8.410e+03, 3.006e+03,
       8.404e+03, 3.202e+03, 3.402e+03, 3.502e+03, 6.411e+03, 3.740e+03,
       3.742e+03, 3.702e+03, 3.704e+03, 3.730e+03, 3.703e+03, 3.804e+03,
       3.808e+03, 3.806e+03, 3.706e+03, 2.802e+03, 3.102e+03, 5.004e+03,
       3.104e+03, 2.806e+03, 1.904e+03, 8.406e+03, 3.744e+03, 2.804e+03,
       3.722e+03, 7.204e+03, 4.202e+03, 4.204e+03, 5.506e+03, 4.206e+03,
       3.208e+03, 5.202e+03, 5.504e+03, 4.402e+03, 4.208e+03, 4.404e+03,
       5.402e+03, 5.404e+03, 9.012e+03, 5.204e+03, 5.008e+03, 5.002e+03,
       5.006e+03, 4.004e+03, 4.804e+03, 4.802e+03, 4.002e+03, 4.602e+03,
       4.604e+03, 9.002e+03, 3.506e+03, 3.504e+03, 3.406e+03, 3.204e+03,
       3.206e+03, 6.012e+03, 8.806e+03, 7.002e+03, 7.006e+03, 6.016e+03,
       6.018e+03, 6.002e+03, 6.420e+03, 6.004e+03, 6.014e+03, 6.006e+03,
       6.024e+03, 6.008e+03, 6.020e+03, 6.022e+03, 6.011e+03, 6.009e+03,
       5.806e+03, 7.004e+03, 9.004e+03, 9.202e+03, 6.802e+03, 6.806e+03,
       6.804e+03, 6.418e+03, 6.430e+03, 6.407e+03, 6.410e+03, 6.409e+03,
       6.404e+03, 7.008e+03, 6.406e+03, 6.402e+03, 8.408e+03, 8.402e+03,
       6.412e+03, 6.413e+03, 6.416e+03, 6.414e+03, 9.006e+03, 8.004e+03,
       8.010e+03, 8.012e+03, 6.489e+03, 8.802e+03, 8.804e+03, 5.704e+03,
       5.702e+03, 7.302e+03, 7.304e+03, 7.202e+03, 7.102e+03, 7.802e+03,
       7.106e+03, 7.502e+03, 7.506e+03, 7.504e+03, 7.702e+03, 7.704e+03,
       7.804e+03, 9.204e+03, 7.208e+03, 9.802e+03, 7.206e+03, 7.104e+03])

19 different food categories... I wonder what these are?

In [14]:
food["food_category_id"].unique()

array([1.600e+01, 1.000e+00, 1.300e+01, 1.100e+01, 2.000e+00, 7.000e+00,
       1.200e+01, 6.000e+00, 9.000e+00, 1.800e+01, 4.000e+00, 5.000e+00,
       1.500e+01, 1.900e+01, 2.500e+01, 1.000e+01,       nan, 2.000e+01,
       1.400e+01, 1.700e+01, 9.602e+03, 1.004e+03, 1.002e+03, 1.006e+03,
       1.008e+03, 1.202e+03, 1.902e+03, 1.820e+03, 1.822e+03, 8.412e+03,
       5.802e+03, 9.007e+03, 9.010e+03, 1.206e+03, 1.204e+03, 1.208e+03,
       1.402e+03, 7.220e+03, 9.404e+03, 9.402e+03, 9.999e+03, 8.008e+03,
       8.006e+03, 5.804e+03, 5.502e+03, 1.602e+03, 1.604e+03, 3.602e+03,
       2.502e+03, 3.720e+03, 6.432e+03, 2.002e+03, 2.004e+03, 9.008e+03,
       2.602e+03, 2.604e+03, 2.006e+03, 3.002e+03, 8.002e+03, 2.008e+03,
       2.206e+03, 2.202e+03, 2.204e+03, 2.010e+03, 2.606e+03, 2.608e+03,
       2.402e+03, 2.404e+03, 3.404e+03, 3.004e+03, 8.410e+03, 3.006e+03,
       8.404e+03, 3.202e+03, 3.402e+03, 3.502e+03, 6.411e+03, 3.740e+03,
       3.742e+03, 3.702e+03, 3.704e+03, 3.730e+03, 3.703e+03, 3.804e+03,
       3.808e+03, 3.806e+03, 3.706e+03, 2.802e+03, 3.102e+03, 5.004e+03,
       3.104e+03, 2.806e+03, 1.904e+03, 8.406e+03, 3.744e+03, 2.804e+03,
       3.722e+03, 7.204e+03, 4.202e+03, 4.204e+03, 5.506e+03, 4.206e+03,
       3.208e+03, 5.202e+03, 5.504e+03, 4.402e+03, 4.208e+03, 4.404e+03,
       5.402e+03, 5.404e+03, 9.012e+03, 5.204e+03, 5.008e+03, 5.002e+03,
       5.006e+03, 4.004e+03, 4.804e+03, 4.802e+03, 4.002e+03, 4.602e+03,
       4.604e+03, 9.002e+03, 3.506e+03, 3.504e+03, 3.406e+03, 3.204e+03,
       3.206e+03, 6.012e+03, 8.806e+03, 7.002e+03, 7.006e+03, 6.016e+03,
       6.018e+03, 6.002e+03, 6.420e+03, 6.004e+03, 6.014e+03, 6.006e+03,
       6.024e+03, 6.008e+03, 6.020e+03, 6.022e+03, 6.011e+03, 6.009e+03,
       5.806e+03, 7.004e+03, 9.004e+03, 9.202e+03, 6.802e+03, 6.806e+03,
       6.804e+03, 6.418e+03, 6.430e+03, 6.407e+03, 6.410e+03, 6.409e+03,
       6.404e+03, 7.008e+03, 6.406e+03, 6.402e+03, 8.408e+03, 8.402e+03,
       6.412e+03, 6.413e+03, 6.416e+03, 6.414e+03, 9.006e+03, 8.004e+03,
       8.010e+03, 8.012e+03, 6.489e+03, 8.802e+03, 8.804e+03, 5.704e+03,
       5.702e+03, 7.302e+03, 7.304e+03, 7.202e+03, 7.102e+03, 7.802e+03,
       7.106e+03, 7.502e+03, 7.506e+03, 7.504e+03, 7.702e+03, 7.704e+03,
       7.804e+03, 9.204e+03, 7.208e+03, 9.802e+03, 7.206e+03, 7.104e+03])

In [15]:
# Get food categories
food_cats = pd.read_csv("data/FoodData_Central_Supporting_Data_csv_2021-04-28/food_category.csv")
food_cats["id"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

## 10 foods we want

To keep things simple, we will reduce the databases from FoodData Central to 10 different foods.

Why these foods?

Because we have images for those foods ready to go.

```python
# These aren't whole foods so we don't want them yet, let's get another list and get those
ten_foods = ["chicken_curry", 
"chicken_wings", 
"fried_rice", 
"grilled_salmon", 
"humburger", 
"ice_cream", 
"pizza",
"ramen", 
"steak", 
"sushi"]

# We want these... (they're whole foods) 
ten_whole_foods = ["chicken_wings",
    "apple",
    "banana",
    "beef", # steak, etc
    "carrots",
    "egg", # whole egg
    "strawberries",
    "blueberries",
    "mushrooms",
    "honey"
]
```

In [186]:
ten_whole_foods = ['apple',
 'banana',
 'beef', # steak etc
 'blueberries',
 'carrots',
 'chicken_wings',
 'egg', # whole egg
 'honey',
 'mushrooms',
 'strawberries']

# hundred_whole_foods = [ 'apple', 'artichoke', 'bbq_sauce', 'bacon', 'bagel', 
#                 'banana', 'beef', 'beer', 'blueberries', 'bread', 
#                 'broccoli', 'butter', 'cabbage', 'candy', 'cantaloupe', 
#                 'carrots', 'cheese', 'roast_chicken', 'chicken_wings', 
#                 'cocktail', 'coconut', 'coffee', 'cookie', 'corn_chips', 
#                 'cream', 'cucumber', 'doughnut', 'egg', 'fish', 'fries', 
#                 'grape', 'guacamole', 'hamburger', 'honey', 'ice_cream', 
#                 'lemon', 'lime', 'lobster', 'mango', 'milk', 'muffin', 
#                 'mushrooms', 'olive_oil', 'olives', 'onion', 'orange', 
#                 'orange_juice', 'pancake', 'pasta', 'pastry', 'pear', 
#                 'bell_pepper', 'pineapple', 'pizza', 'pomegranate', 'popcorn', 
#                 'potato', 'prawns', 'pretzel', 'pumpkin', 'radish', 'rice', 
#                 'salad', 'salt', 'sandwich', 'sausages', 'soft_drink', 
#                 'spinach', 'squid', 'strawberries', 'sushi', 'tea', 
#                 'tomato', 'tomato_sauce', 'waffle', 'watermelon', 'wine', 
#                 'zucchini', 'avocado', 'asparagus', 'beetroot', 'cauliflower', 
#                 'celery', 'cherries', 'corn', 'dates', 'dragon_fruit', 
#                 'durian', 'eggplant', 'garlic', 'ginger', 'green_beans', 
#                 'kiwi', 'lettuce', 'papaya', 'peach', 'peas', 
#                 'raspberries', 'sweet_potato', 'turnip' ]

hundred_whole_foods = [
    # =========================
    # FRUITS - 25
    # =========================
    'apple',              # original
    'banana',             # original
    'blueberries',        # original
    'strawberries',       # original
    'orange',
    'mango',
    'pineapple',
    'watermelon',
    'grapes',
    'pear',
    'peach',
    'kiwi',
    'papaya',
    'avocado',
    'pomegranate',
    'cherries',
    'raspberries',
    'blackberries',
    'cantaloupe',
    'grapefruit',
    'plum',
    'apricot',
    'figs',
    'dates',
    'coconut',

    # =========================
    # VEGETABLES - 25
    # =========================
    'carrots',            # original
    'mushrooms',          # original
    'broccoli',
    'cauliflower',
    'cabbage',
    'spinach',
    'lettuce',
    'cucumber',
    'tomato',
    'bell_pepper',
    'onion',
    'garlic',
    'potato',
    'sweet_potato',
    'pumpkin',
    'zucchini',
    'eggplant',
    'asparagus',
    'celery',
    'green_beans',
    'peas',
    'corn',
    'beetroot',
    'radish',
    'turnip',

    # =========================
    # MEAT / SEAFOOD / EGG - 20
    # =========================
    'beef',               # original
    'chicken_wings',      # original
    'egg',                # original
    'chicken_breast',
    'chicken_thigh',
    'pork_chop',
    'bacon',
    'turkey_breast',
    'salmon',
    'tuna',
    'shrimp',
    'crab',
    'lobster',
    'squid',
    'cod',
    'sardines',
    'tilapia',
    'lamb_chop',
    'duck_breast',
    'ham',

    # =========================
    # LEGUMES / NUTS / SEEDS - 15
    # =========================
    'tofu',
    'lentils',
    'chickpeas',
    'kidney_beans',
    'black_beans',
    'peanuts',
    'almonds',
    'cashews',
    'walnuts',
    'pistachios',
    'sunflower_seeds',
    'pumpkin_seeds',
    'sesame_seeds',
    'chia_seeds',
    'soybeans',

    # =========================
    # DAIRY / GRAINS / OTHER - 15
    # =========================
    'honey',              # original
    'milk',
    'yogurt',
    'cheddar_cheese',
    'mozzarella_cheese',
    'butter',
    'rice',
    'brown_rice',
    'oats',
    'bread',
    'pasta',
    'noodles',
    'bagel',
    'popcorn',
    'peanut_butter'
]

In [187]:
food.head()

AttributeError: 'str' object has no attribute 'head'

In [188]:
# Foundation food is the ground truth for a certain type of food, excludes some details about the food
# E.g. the data_type foundation_food for Chicken will the the original unique ID for chicken
foundation_food = food[(food["data_type"] == "foundation_food") | (food["data_type"] == "survey_fndds_food")]
len(foundation_food)

TypeError: string indices must be integers, not 'str'

In [189]:
foundation_food[foundation_food["description"].str.contains("blue")]

,fdc_id,data_type,description,food_category_id,publication_date
42186,2263889,foundation_food,"blueberries, raw",9.0,2022-04-28
43441,2346411,foundation_food,"blueberries, raw",9.0,2022-10-28
60660,2684446,foundation_food,"crustaceans, crab, blue swimming, lump, pasteu...",15.0,2024-04-18
88312,2705705,survey_fndds_food,"cheese, blue or roquefort",1602.0,2022-10-28
90605,2707998,survey_fndds_food,"pie, blueberry",5502.0,2022-10-28
91805,2709198,survey_fndds_food,"blueberries, dried",6016.0,2022-10-28
91882,2709275,survey_fndds_food,"blueberries, raw",6011.0,2022-10-28
91884,2709277,survey_fndds_food,"blueberries, frozen",6011.0,2022-10-28
91885,2709278,survey_fndds_food,blueberry pie filling,8806.0,2022-10-28
91930,2709323,survey_fndds_food,blueberry juice,7006.0,2022-10-28
92804,2710197,survey_fndds_food,blue or roquefort cheese dressing,8012.0,2022-10-28
92823,2710216,survey_fndds_food,"blue or roquefort cheese dressing, light",8012.0,2022-10-28
92836,2710229,survey_fndds_food,"blue or roquefort cheese dressing, fat free",8012.0,2022-10-28
92882,2710275,survey_fndds_food,blueberry syrup,8806.0,2022-10-28

In [190]:
foundation_foods = foundation_food["description"]
foundation_foods[20:40]

4153               peanut butter, smooth style, with salt
4329                             cheese, parmesan, grated
4491    cheese, pasteurized process, american, vitamin...
4580    grapefruit juice, white, canned or bottled, un...
4723                                 peaches, yellow, raw
4817    seeds, sunflower seed kernels, dry roasted, wi...
4951      sausage, italian, pork, mild, cooked, pan-fried
5164                  bread, white, commercially prepared
5285          sausage, turkey, breakfast links, mild, raw
5428                                        cheese, swiss
5489    kale, frozen, cooked, boiled, drained, without...
5751    carrots, frozen, unprepared (includes foods fo...
5991                            mustard, prepared, yellow
6198                                figs, dried, uncooked
6339                                kiwifruit, green, raw
6491                              melons, cantaloupe, raw
6650                                      nectarines, raw
6794    oranges, raw, navels (includes foods for usda'...
6992                                    strawberries, raw
7216                         lettuce, cos or romaine, raw
Name: description, dtype: str

In [191]:
# Found a list of the foundation foods we're going to start with!
foundation_foods_list = list(foundation_foods)
for food in foundation_foods_list:
    if "blue" in food:
        print(food)

blueberries, raw
blueberries, raw
crustaceans, crab, blue swimming, lump, pasteurized, refrigerated
cheese, blue or roquefort
pie, blueberry
blueberries, dried
blueberries, raw
blueberries, frozen
blueberry pie filling
blueberry juice
blue or roquefort cheese dressing
blue or roquefort cheese dressing, light
blue or roquefort cheese dressing, fat free
blueberry syrup

In [192]:
# food.loc[(food["description"].str.contains("chicken", case=False)) & (food["description"].str.contains("drumstick", case=False))][-10:]
# Find chicken in foundation food
for food in foundation_foods:
    if "chicken" in food.lower():
        print(food)

chicken, broilers or fryers, drumstick, meat only, cooked, braised
chicken, broiler or fryers, breast, skinless, boneless, meat only, cooked, braised
chicken, ground, with additives, raw
chicken, breast, boneless, skinless, raw
chicken, thigh, boneless, skinless, raw
chicken, drumstick, meat and skin, raw
chicken, thigh, meat and skin, raw
chicken, wing, meat and skin, raw
chicken, breast, meat and skin, raw
lunchmeat, chicken breast, sliced
mock chicken legs
chicken, ns as to part and cooking method, ns as to skin eaten
chicken, ns as to part and cooking method, skin eaten
chicken, ns as to part and cooking method, skin not eaten
chicken, ns as to part, baked, broiled, or roasted, ns as to skin eaten
chicken, ns as to part, baked, broiled, or roasted, skin eaten
chicken, ns as to part, baked, broiled, or roasted, skin not eaten
chicken, ns as to part, rotisserie, ns as to skin eaten
chicken, ns as to part, rotisserie, skin eaten
chicken, ns as to part, rotisserie, skin not eaten
chicken, ns as to part, stewed, ns as to skin eaten
chicken, ns as to part, stewed, skin eaten
chicken, ns as to part, stewed, skin not eaten
chicken, ns as to part, grilled without sauce, ns as to skin eaten
chicken, ns as to part, grilled without sauce, skin eaten
chicken, ns as to part, grilled without sauce, skin not eaten
chicken, ns as to part, grilled with sauce, ns as to skin eaten
chicken, ns as to part, grilled with sauce, skin eaten
chicken, ns as to part, grilled with sauce, skin not eaten
chicken, ns as to part, sauteed, skin eaten
chicken, ns as to part, sauteed, skin not eaten
chicken, ns as to part, fried, coated, skin / coating eaten
chicken, ns as to part, fried, coated, skin / coating not eaten
chicken, ns as to part, baked, coated, skin / coating eaten
chicken, ns as to part, baked, coated, skin / coating not eaten
chicken breast, ns as to cooking method, skin eaten
chicken breast, ns as to cooking method, skin not eaten
chicken breast, baked, broiled, or roasted, skin eaten, from raw
chicken breast, baked, broiled, or roasted, skin not eaten, from raw
chicken breast, baked or broiled, skin eaten, from pre-cooked
chicken breast, baked or broiled, skin not eaten, from pre-cooked
chicken breast, baked or broiled, skin eaten, from fast food / restaurant
chicken breast, baked or broiled, skin not eaten, from fast food / restaurant
chicken breast, baked, broiled, or roasted with marinade, skin eaten, from raw
chicken breast, baked, broiled, or roasted with marinade, skin not eaten, from raw
chicken breast, rotisserie, skin eaten
chicken breast, rotisserie, skin not eaten
chicken breast, stewed, skin eaten
chicken breast, stewed, skin not eaten
chicken breast, grilled without sauce, skin eaten
chicken breast, grilled without sauce, skin not eaten
chicken breast, grilled with sauce, skin eaten
chicken breast, grilled with sauce, skin not eaten
chicken breast, sauteed, skin eaten
chicken breast, sauteed, skin not eaten
chicken breast, fried, coated, skin / coating eaten, from raw
chicken breast, fried, coated, skin / coating not eaten, from raw
chicken breast, fried, coated, prepared skinless, coating eaten, from raw
chicken breast, fried, coated, skin / coating eaten, from pre-cooked
chicken breast, fried, coated, skin / coating not eaten, from pre-cooked
chicken breast, fried, coated, skin / coating eaten, from fast food / restaurant
chicken breast, fried, coated, skin / coating not eaten, from fast food / restaurant
chicken breast, baked, coated, skin / coating eaten
chicken breast, baked, coated, skin / coating not eaten
chicken leg, drumstick and thigh, ns as to cooking method, skin eaten
chicken leg, drumstick and thigh, ns as to cooking method, skin not eaten
chicken leg, drumstick and thigh, baked or broiled, skin eaten
chicken leg, drumstick and thigh, baked or broiled, skin not eaten
chicken leg, drumstick and thigh, rotisserie, skin eaten
chicken leg, drumstick and thigh, rotisserie, skin not eaten
chicken leg, drumstick and thigh, stewed, skin eaten
chicken leg, drumstick and thigh, stewed, skin not eaten
chicken leg, drumstick and thigh, grilled without sauce, skin eaten
chicken leg, drumstick and thigh, grilled without sauce, skin not eaten
chicken leg, drumstick and thigh, grilled with sauce, skin eaten
chicken leg, drumstick and thigh, grilled with sauce, skin not eaten
chicken leg, drumstick and thigh, sauteed, skin eaten
chicken leg, drumstick and thigh, sauteed, skin not eaten
chicken leg, drumstick and thigh, fried, coated, skin / coating eaten
chicken leg, drumstick and thigh, fried, coated, skin / coating not eaten
chicken leg, drumstick and thigh, baked, coated, skin / coating eaten
chicken leg, drumstick and thigh, baked, coated, skin / coating not eaten
chicken drumstick, ns as to cooking method, skin eaten
chicken drumstick, ns as to cooking method, skin not eaten
chicken drumstick, baked, broiled, or roasted, skin eaten, from raw
chicken drumstick, baked, broiled, or roasted, skin not eaten, from raw
chicken drumstick, baked or broiled, skin eaten, from pre-cooked
chicken drumstick, baked or broiled, skin not eaten, from pre-cooked
chicken drumstick, baked or broiled, skin eaten, from fast food / restaurant
chicken drumstick, baked or broiled, skin not eaten, from fast food / restaurant
chicken drumstick, rotisserie, skin eaten
chicken drumstick, rotisserie, skin not eaten
chicken drumstick, grilled without sauce, skin eaten
chicken drumstick, grilled without sauce, skin not eaten
chicken drumstick, grilled with sauce, skin eaten
chicken drumstick, grilled with sauce, skin not eaten
chicken drumstick, stewed, skin eaten
chicken drumstick, stewed, skin not eaten
chicken drumstick, sauteed, skin eaten
chicken drumstick, sauteed, skin not eaten
chicken drumstick, fried, coated, skin / coating eaten, from raw
chicken drumstick, fried, coated, skin / coating not eaten, from raw
chicken drumstick, fried, coated, prepared skinless, coating eaten, from raw
chicken drumstick, fried, coated, skin / coating eaten, from pre-cooked
chicken drumstick, fried, coated, skin / coating not eaten, from pre-cooked
chicken drumstick, fried, coated, skin / coating eaten, from fast food / restaurant
chicken drumstick, fried, coated, skin / coating not eaten, from fast food / restaurant
chicken drumstick, baked, coated, skin / coating eaten
chicken drumstick, baked, coated, skin / coating not eaten
chicken thigh, ns as to cooking method, skin eaten
chicken thigh, ns as to cooking method, skin not eaten
chicken thigh, baked, broiled, or roasted, skin eaten, from raw
chicken thigh, baked, broiled, or roasted, skin not eaten, from raw
chicken thigh, baked or broiled, skin eaten, from pre-cooked
chicken thigh, baked or broiled, skin not eaten, from pre-cooked
chicken thigh, baked or broiled, skin eaten, from fast food / restaurant
chicken thigh, baked or broiled, skin not eaten, from fast food / restaurant
chicken thigh, rotisserie, skin eaten
chicken thigh, rotisserie, skin not eaten
chicken thigh, stewed, skin eaten
chicken thigh, stewed, skin not eaten
chicken thigh, grilled without sauce, skin eaten
chicken thigh, grilled without sauce, skin not eaten
chicken thigh, grilled with sauce, skin eaten
chicken thigh, grilled with sauce, skin not eaten
chicken thigh, sauteed, skin eaten
chicken thigh, sauteed, skin not eaten
chicken thigh, fried, coated, skin / coating eaten, from raw
chicken thigh, fried, coated, skin / coating not eaten, from raw
chicken thigh, fried, coated, prepared skinless, coating eaten, from raw
chicken thigh, fried, coated, skin / coating eaten, from pre-cooked
chicken thigh, fried, coated, skin / coating not eaten, from pre-cooked
chicken thigh, fried, coated, skin / coating eaten, from fast food
chicken thigh, fried, coated, skin / coating not eaten, from fast food
chicken thigh, fried, coated, skin / coating eaten, from restaurant
chicken thigh, fried, coated, skin / coating not eaten, from restaurant
chicken thigh, baked, coated, skin / coating eaten
chicken thigh, baked, coated, skin / coating not eaten
chicken wing, ns as to cooking method
chicken wing, baked, broiled, or roasted, from raw
chicken wing, baked or broiled, from pre-cooked
chicken wing, baked or broiled, from fast food / restaurant
chicken wing, rotisserie
chicken wing, stewed
chicken wing, grilled without sauce
chicken wing, grilled with sauce
chicken wing, sauteed
chicken wing, fried, coated, from raw
chicken wing, fried, coated, from pre-cooked
chicken wing, fried, coated, from fast food
chicken wing, fried, coated, from restaurant
chicken wing, baked, coated
chicken "wings" with hot sauce, from fast food / restaurant
chicken "wings" with other sauces or seasoning, from fast food / restaurant
chicken "wings", plain, from fast food / restaurant
chicken "wings" with hot sauce, from precooked
chicken "wings" with other sauces or seasoning, from precooked
chicken "wings", plain, from precooked
chicken "wings" with hot sauce, from other sources
chicken "wings" with other sauces or seasoning, from other sources
chicken "wings", plain, from other sources
chicken "wings", boneless, with hot sauce, from fast food / restaurant
chicken "wings", boneless, with hot sauce, from other sources
chicken, back
chicken, neck or ribs
chicken, tail
chicken skin
chicken feet
chicken, canned, meat only
chicken, chicken roll, roasted
chicken patty, breaded
chicken fillet, breaded
chicken fillet, grilled
chicken, ground
chicken nuggets, nfs
chicken nuggets, from fast food
chicken nuggets, from restaurant
chicken nuggets, from school lunch
chicken nuggets, from frozen
chicken nuggets, from other sources
chicken tenders or strips, nfs
chicken tenders or strips, breaded, from fast food
chicken tenders or strips, breaded, from restaurant
chicken tenders or strips, breaded, from school lunch
chicken tenders or strips, breaded, from frozen
chicken tenders or strips, breaded, from other sources
baby toddler chicken
liver, chicken
turkey or chicken sausage
turkey or chicken sausage, reduced sodium
turkey or chicken and pork sausage
chicken, prepackaged or deli, luncheon meat
chicken, prepackaged or deli, luncheon meat, reduced sodium
chicken salad spread
chicken or turkey cacciatore
stewed chicken with tomato-based sauce, mexican style
chili with chicken and beans
chili with chicken
chicken with gravy
chicken or turkey fricassee
chicken or turkey with cream sauce
chicken or turkey with mushroom sauce
chicken or turkey with teriyaki
barbecue chicken
sweet and sour chicken or turkey
sweet and sour chicken or turkey, without vegetables
chicken curry
chicken curry with rice
chicken with mole sauce
chicken or turkey with cheese sauce
chicken or turkey cordon bleu
chicken or turkey parmigiana
orange chicken
sesame chicken
chicken kiev
stuffed chicken, drumstick or breast, puerto rican style
chicken or turkey hash
chicken or turkey and potatoes with gravy
chicken or turkey and noodles, no sauce
chicken or turkey and noodles with gravy
chicken or turkey and noodles with mushroom sauce
chicken or turkey and noodles with cream or white sauce
chicken or turkey and noodles with cheese sauce
chicken or turkey tetrazzini
chicken or turkey and noodles with tomato-based sauce
chicken or turkey and noodles with soy-based sauce
chicken or turkey and rice, no sauce
biryani with chicken
chicken or turkey and rice with cream sauce
chicken or turkey and rice with mushroom sauce
chicken or turkey and rice with tomato-based sauce
chicken or turkey and rice with soy-based sauce
chicken or turkey with dumplings
chicken or turkey with stuffing
chicken or turkey cake, patty, or croquette
chicken or turkey souffle
meat loaf made with chicken or turkey
meat loaf made with chicken or turkey, with tomato-based sauce
chicken or turkey, potatoes, corn, and cheese, with gravy
chicken or turkey, potatoes, and vegetables including carrots, broccoli, and/or dark-green leafy; no sauce
chicken or turkey, potatoes, and vegetables excluding carrots, broccoli, and dark-green leafy; no sauce
chicken or turkey, potatoes, and vegetables including carrots, broccoli, and/or dark-green leafy; gravy
chicken or turkey, potatoes, and vegetables excluding carrots, broccoli, and dark-green leafy; gravy
chicken or turkey, potatoes, and vegetables including carrots, broccoli, and/or dark-green leafy; cream sauce, white sauce, or mushroom sauce
chicken or turkey, potatoes, and vegetables excluding carrots, broccoli, and dark-green leafy; cream sauce, white sauce, or mushroom sauce
chicken or turkey, potatoes, and vegetables including carrots, broccoli, and/or dark-green leafy; cheese sauce
chicken or turkey, potatoes, and vegetables excluding carrots, broccoli, and dark-green leafy; cheese sauce
chicken or turkey, potatoes, and vegetables including carrots, broccoli, and/or dark-green leafy; tomato-based sauce
chicken or turkey, potatoes, and vegetables excluding carrots, broccoli, and dark-green leafy; tomato-based sauce
stew, chicken, with pasta
stew, chicken
chicken or turkey, noodles, and vegetables including carrots, broccoli, and/or dark-green leafy; no sauce
chicken or turkey, noodles, and vegetables excluding carrots, broccoli, and dark-green leafy; no sauce
chicken or turkey, noodles, and vegetables including carrots, broccoli, and/or dark-green leafy; gravy
chicken or turkey, noodles, and vegetables excluding carrots, broccoli, and dark-green leafy; gravy
chicken or turkey, noodles, and vegetables including carrots, broccoli, and/or dark-green leafy; cream sauce, white sauce, or mushroom sauce
chicken or turkey, noodles, and vegetables excluding carrots, broccoli, and/or dark-green leafy; cream sauce, white sauce, or mushroom sauce
chicken or turkey, noodles, and vegetables including carrots, broccoli, and/or dark-green leafy; tomato-based sauce
chicken or turkey, noodles, and vegetables excluding carrots, broccoli, and dark-green leafy; tomato-based sauce
chicken or turkey chow mein or chop suey with noodles
chicken or turkey, noodles, and vegetables including carrots, broccoli, and/or dark-green leafy; cheese sauce
chicken or turkey, noodles, and vegetables excluding carrots, broccoli, and dark-green leafy; cheese sauce
chicken or turkey, rice, and vegetables including carrots, broccoli, and/or dark-green leafy; no sauce
chicken or turkey, rice, and vegetables excluding carrots, broccoli, and dark-green leafy; no sauce
chicken or turkey, rice, and vegetables including carrots, broccoli, and/or dark-green leafy; gravy
chicken or turkey, rice, and vegetables excluding carrots, broccoli, and dark-green leafy; gravy
chicken or turkey, rice, corn, and cheese, with gravy
chicken or turkey, rice, and vegetables including carrots, broccoli, and/or dark-green leafy; soy-based sauce
chicken or turkey, rice, and vegetables excluding carrots, broccoli, and dark-green leafy; soy-based sauce
chicken or turkey, rice, and vegetables including carrots, broccoli, and/or dark-green leafy; cream sauce, white sauce, or mushroom sauce
chicken or turkey, rice, and vegetables excluding carrots, broccoli, and dark-green leafy; cream sauce, white sauce, or mushroom sauce
chicken or turkey, rice, and vegetables including carrots, broccoli, and/or dark-green leafy; cheese sauce
chicken or turkey, rice, and vegetables excluding carrots, broccoli, and dark-green leafy; cheese sauce
chicken or turkey, rice, and vegetables including carrots, broccoli, and/or dark-green leafy; tomato-based sauce
chicken or turkey, rice, and vegetables excluding carrots, broccoli, and dark-green leafy; tomato-based sauce
pot pie, chicken
chicken or turkey, stuffing, and vegetables including carrots, broccoli, and/or dark-green leafy; no sauce
chicken or turkey,stuffing, and vegetables excluding carrots, broccoli, and dark green leafy; no sauce
chicken or turkey, stuffing, and vegetables including carrots, broccoli, and/or dark-green leafy; gravy
chicken or turkey, stuffing, and vegetables excluding carrots, broccoli, and dark-green leafy; gravy
chicken or turkey, dumplings, and vegetables including carrots, broccoli, and/or dark green leafy; gravy
chicken or turkey, dumplings, and vegetables excluding carrots, broccoli, and dark green leafy; gravy
chicken fricassee, puerto rican style
chicken or turkey and vegetables including carrots, broccoli, and/or dark-green leafy; no potatoes, no sauce
chicken or turkey and vegetables excluding carrots, broccoli, and dark-green leafy; no potatoes, no sauce
chicken or turkey shish kabob with vegetables, excluding potatoes
chicken or turkey creole, without rice
chicken or turkey and vegetables including carrots, broccoli, and/or dark-green leafy; no potatoes, gravy
chicken or turkey and vegetables excluding carrots, broccoli, and dark-green leafy; no potatoes, gravy
chicken or turkey a la king with vegetables including carrots, broccoli, and/or dark-green leafy; no potatoes, cream, white, or soup-based sauce
chicken or turkey a la king with vegetables excluding carrorts, broccoli, and dark-green leafy; no potatoes, cream, white, or soup-based sauce
chicken or turkey divan
chicken or turkey and vegetables including carrots, broccoli, and/or dark-green leafy; no potatoes, soy-based sauce
chicken or turkey and vegetables excluding carrots, broccoli, and dark-green leafy; no potatoes, soy-based sauce
chicken or turkey and vegetables including carrots, broccoli, and/or dark-green leafy; no potatoes, tomato-based sauce
chicken or turkey and vegetables excluding carrots, broccoli, and dark-green leafy; no potatoes, tomato-based sauce
general tso chicken
kung pao chicken
almond chicken
chicken or turkey chow mein or chop suey, no noodles
chicken or turkey salad, made with mayonnaise
chicken or turkey salad with nuts and/or fruits
chicken or turkey salad with egg
chicken or turkey salad, made with light mayonnaise
chicken or turkey salad, made with mayonnaise-type salad dressing
chicken or turkey salad, made with light mayonnaise-type salad dressing
chicken or turkey salad, made with creamy dressing
chicken or turkey salad, made with light creamy dressing
chicken or turkey salad, made with italian dressing
chicken or turkey salad, made with light italian dressing
chicken or turkey salad, made with any type of fat free dressing
chicken or turkey garden salad, chicken and/or turkey, tomato and/or carrots, other vegetables, no dressing
chicken or turkey garden salad, chicken and/or turkey, other vegetables excluding tomato and carrots, no dressing
chicken or turkey garden salad with bacon and cheese, chicken and/or turkey, bacon, cheese, lettuce and/or greens, tomato and/or carrots, other vegetables, no dressing
chicken or turkey, breaded, fried, garden salad with bacon and cheese, chicken and/or turkey, bacon, cheese, lettuce and/or greens, tomato and/or carrots, other vegetables, no dressing
chicken or turkey garden salad with cheese, chicken and/or turkey, cheese, lettuce and/or greens, tomato and/or carrots, other vegetables, no dressing
chicken or turkey, breaded, fried, garden salad with cheese, chicken and/or turkey, cheese, lettuce and/or greens, tomato and/or carrots, other vegetables, no dressing
asian chicken or turkey garden salad, chicken and/or turkey, lettuce, fruit, nuts, no dressing
asian chicken or turkey garden salad with crispy noodles, chicken and/or turkey, lettuce, fruit, nuts, crispy noodles, no dressing
chicken or turkey caesar garden salad, chicken and/or turkey, lettuce, tomato, cheese, no dressing
chicken or turkey, breaded, fried, caesar garden salad, chicken and/or turkey, lettuce, tomatoes, cheese, no dressing
chicken or turkey and vegetables including carrots, broccoli, and/or dark-green leafy; no potatoes, cheese sauce
chicken or turkey and vegetables excluding carrots, broccoli, and dark-green leafy; no potatoes, cheese sauce
chicken or turkey fricassee, with sauce, no potatoes, potatoes reported separately, puerto rican style
chicken or turkey fricassee, no sauce, no potatoes, puerto rican style

In [193]:
chicken_wing_id = int(foundation_food.loc[foundation_food["description"].str.contains("Chicken", case=False)].iloc[0]["fdc_id"])
chicken_wing_id

331897

In [194]:
apple_id = int(foundation_food.loc[foundation_food["description"].str.contains("Apple", case=False)].iloc[0]["fdc_id"])
apple_id

1105430

In [195]:
food_nutrient[food_nutrient["fdc_id"] == chicken_wing_id]

,id,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acquired,nutrient_name
41714,2259068,331897,1303,0.003,5.0,1.0,0.002,0.004,0.003,NaN,2010.0,tfa 16:1 t
41715,2259065,331897,1280,0.008,5.0,1.0,0.008,0.009,0.008,NaN,2010.0,pufa 22:5 n-3 (dpa)
41716,2259076,331897,1404,0.045,5.0,1.0,0.035,0.059,0.042,NaN,2010.0,"pufa 18:3 n-3 c,c,c (ala)"
41717,2259059,331897,1261,0.002,5.0,1.0,0.001,0.003,0.002,NaN,2010.0,sfa 8:0
41718,2259106,331897,1109,0.170,1.0,1.0,NaN,NaN,0.170,NaN,2010.0,vitamin e (alpha-tocopherol)
...,...,...,...,...,...,...,...,...,...,...,...,...
41806,2259112,331897,1167,5.050,5.0,1.0,4.890,5.240,5.050,NaN,2010.0,niacin
41807,2259074,331897,1329,0.021,NaN,4.0,NaN,NaN,NaN,NaN,NaN,"fatty acids, total trans-monoenoic"
41808,2259138,331897,1330,0.008,NaN,4.0,NaN,NaN,NaN,NaN,NaN,"fatty acids, total trans-dienoic"
41809,13338545,331897,2047,149.000,NaN,1.0,NaN,NaN,NaN,NaN,NaN,energy (atwater general factors)
41810,13338447,331897,2048,156.000,NaN,49.0,NaN,NaN,NaN,NaN,NaN,energy (atwater specific factors)

## Get protein, carb, fat IDs

See this document for info on foundation foods and their nutrients - https://fdc.nal.usda.gov/docs/Foundation_Foods_Documentation_Apr2021.pdf

* Carbohydrate, by difference = total carbohydrates

In [196]:
nutrient[(nutrient["name"].str.contains("protein", case=False)) | \
         (nutrient["name"].str.contains("carbohydrate", case=False)) | \
         (nutrient["name"].str.contains("fat", case=False)) | \
         (nutrient["name"].str.contains("energy", case=False))]

,id,name,unit_name,nutrient_nbr,rank
0,2047,Energy (Atwater General Factors),KCAL,957.0,280.0
1,2048,Energy (Atwater Specific Factors),KCAL,958.0,290.0
4,1003,Protein,G,203.0,600.0
5,1004,Total lipid (fat),G,204.0,800.0
6,1005,"Carbohydrate, by difference",G,205.0,1110.0
9,1008,Energy,KCAL,208.0,300.0
50,1049,"Solids, non-fat",G,253.0,999999.0
51,1050,"Carbohydrate, by summation",G,205.2,1120.0
54,1053,Adjusted Protein,G,257.0,700.0
63,1062,Energy,kJ,268.0,400.0
73,1072,"Carbohydrate, other",G,284.0,NaN
86,1085,Total fat (NLEA),G,298.0,900.0
258,1257,"Fatty acids, total trans",G,605.0,15400.0
259,1258,"Fatty acids, total saturated",G,606.0,9700.0
291,1291,"Fatty acids, other than 607-615, 617-621, 624-...",G,644.0,999999.0
292,1292,"Fatty acids, total monounsaturated",G,645.0,11400.0
293,1293,"Fatty acids, total polyunsaturated",G,646.0,12900.0
318,1318,"Fatty acids, saturated, other",G,677.0,999999.0
319,1319,"Fatty acids, monounsat., other",G,678.0,999999.0
320,1320,"Fatty acids, polyunsat., other",G,679.0,999999.0
326,1326,"Fatty acids, total sat., NLEA",G,690.0,999999.0
327,1327,"Fatty acids, total monounsat., NLEA",G,691.0,999999.0
328,1328,"Fatty acids, total polyunsat., NLEA",G,692.0,999999.0
329,1329,"Fatty acids, total trans-monoenoic",G,693.0,15500.0
330,1330,"Fatty acids, total trans-dienoic",G,694.0,15601.0
331,1331,"Fatty acids, total trans-polyenoic",G,695.0,15619.0
450,2039,Carbohydrates,G,956.0,1100.0

In [197]:
target_nutrients = nutrient[nutrient["name"].isin(["Protein", "Total lipid (fat)", "Carbohydrate, by difference", "Energy (Atwater Specific Factors)"])]

# target_nutrients = target_nutrients[
#     ~((nutrient["name"] == "Energy") & (nutrient["unit_name"] == "kJ"))
# ]
target_nutrients

     id                               name unit_name  nutrient_nbr    rank
1  2048  Energy (Atwater Specific Factors)      KCAL         958.0   290.0
4  1003                            Protein         G         203.0   600.0
5  1004                  Total lipid (fat)         G         204.0   800.0
6  1005        Carbohydrate, by difference         G         205.0  1110.0

In [198]:
target_nutrient_dict = {
    # Modern IDs (foundation foods)
    1003: "protein",
    1004: "fat",
    1005: "carbohydrate",
    1008: "energy_kcal",      # standard Energy (kcal)
    2048: "energy_kcal",      # Energy (Atwater Specific Factors)
    # Legacy IDs (survey/FNDDS foods)
    203: "protein",
    204: "fat",
    205: "carbohydrate",
    208: "energy_kcal",
}
target_nutrient_dict

{1003: 'protein',
 1004: 'fat',
 1005: 'carbohydrate',
 1008: 'energy_kcal',
 2048: 'energy_kcal',
 203: 'protein',
 204: 'fat',
 205: 'carbohydrate',
 208: 'energy_kcal'}

## Get target food protein, fat, carbohydrates

We want to now index on the target foods and the target nutrients and retrieve their values for each food/nutrient.

E.g.

```python
{"food_1": {"protein": 100,
            "carbohydrate": 50,
            "fat": 20},
 "food_2": ...

...}
```

In [199]:
list(target_nutrient_dict.keys())

[1003, 1004, 1005, 1008, 2048, 203, 204, 205, 208]

In [200]:
food_nutrient

,id,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acquired,nutrient_name
0,2201847,319877,1051,56.30,1.0,1.0,NaN,NaN,NaN,NaN,NaN,water
1,2201845,319877,1002,1.28,1.0,1.0,NaN,NaN,NaN,NaN,NaN,nitrogen
2,2201846,319877,1004,19.00,1.0,1.0,NaN,NaN,NaN,NaN,NaN,total lipid (fat)
3,2201844,319877,1007,1.98,1.0,1.0,NaN,NaN,NaN,NaN,NaN,ash
4,2201852,319878,1091,188.00,1.0,1.0,NaN,NaN,NaN,NaN,NaN,"phosphorus, p"
...,...,...,...,...,...,...,...,...,...,...,...,...
523479,34489112,2710814,208,892.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
523480,34489151,2710814,601,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
523481,34489135,2710814,337,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
523482,34489121,2710814,304,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
523483,34489143,2710814,418,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [201]:
food_nutrient[(food_nutrient["nutrient_id"].isin(list(target_nutrient_dict.keys())))]

,id,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acquired,nutrient_name
2,2201846,319877,1004,19.00,1.0,1.0,NaN,NaN,NaN,NaN,NaN,total lipid (fat)
16,2201859,319882,1004,18.70,1.0,1.0,NaN,NaN,NaN,NaN,NaN,total lipid (fat)
28,2201873,319892,1004,16.60,1.0,1.0,NaN,NaN,NaN,NaN,NaN,total lipid (fat)
43,2201886,319899,1004,19.10,1.0,1.0,NaN,NaN,NaN,NaN,NaN,total lipid (fat)
97,2201942,319908,1004,18.20,1.0,1.0,NaN,NaN,NaN,NaN,NaN,total lipid (fat)
...,...,...,...,...,...,...,...,...,...,...,...,...
523400,34489046,2710813,205,17.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
523452,34489111,2710814,205,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
523464,34489110,2710814,204,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
523469,34489109,2710814,203,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
523479,34489112,2710814,208,892.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [202]:
unique_nutrients = food_nutrient[
    food_nutrient["nutrient_id"].isin(list(target_nutrient_dict.keys()))
]["nutrient_id"].unique()

print(unique_nutrients)

[1004 1003 1008 1005 2048  204  208  205  203]

In [203]:
food_nutrient.dtypes

id                     int64
fdc_id                 int64
nutrient_id            int64
amount               float64
data_points          float64
derivation_id        float64
min                  float64
max                  float64
median               float64
footnote              object
min_year_acquired    float64
nutrient_name            str
dtype: object

In [204]:
# Find nutrition for chicken_wing_id (protein, fat, carb)
food_nutrient[(food_nutrient["fdc_id"] == chicken_wing_id) & (food_nutrient["nutrient_id"].isin(list(target_nutrient_dict.keys())))]

,id,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acquired,nutrient_name
41746,2259100,331897,1008,156.00,NaN,49.0,NaN,NaN,NaN,NaN,NaN,energy
41750,2259098,331897,1004,5.95,6.0,1.0,5.54,6.33,5.93,NaN,2010.0,total lipid (fat)
41782,2259079,331897,1003,23.90,NaN,49.0,23.00,24.60,24.10,NaN,NaN,protein
41793,2259099,331897,1005,0.00,NaN,49.0,NaN,NaN,NaN,NaN,NaN,"carbohydrate, by difference"
41810,13338447,331897,2048,156.00,NaN,49.0,NaN,NaN,NaN,NaN,NaN,energy (atwater specific factors)

In [205]:
sorted(list(foundation_foods))

['abalone',
 'adobo, with noodles',
 'adobo, with rice',
 'agave liquid sweetener',
 'alaska pollock, raw',
 'alcoholic coffee drink',
 'alcoholic malt beverage',
 'alcoholic malt beverage, sweetened',
 'alfalfa sprouts, raw',
 'alfredo sauce',
 'alfredo sauce with added vegetables',
 'alfredo sauce with meat',
 'alfredo sauce with meat and added vegetables',
 'alfredo sauce with poultry',
 'alfredo sauce with poultry and added vegetables',
 'alfredo sauce with seafood',
 'alfredo sauce with seafood and added vegetables',
 'almond butter',
 'almond butter and jelly sandwich, on wheat bread',
 'almond butter and jelly sandwich, on white bread',
 'almond butter sandwich, on wheat bread',
 'almond butter sandwich, on white bread',
 'almond butter, creamy',
 'almond butter, lower sodium',
 'almond chicken',
 'almond milk, chocolate',
 'almond milk, nfs',
 'almond milk, sweetened',
 'almond milk, unsweetened',
 'almond milk, unsweetened, plain, refrigerated',
 'almond milk, unsweetened, plain, shelf stable',
 'almond milk, unsweetened, plain, shelf stable',
 'almond oil',
 'almond paste',
 'almonds, chocolate covered candy',
 'almonds, flavored',
 'almonds, honey roasted',
 'almonds, lightly salted',
 'almonds, nfs',
 'almonds, salted',
 'almonds, unroasted',
 'almonds, unsalted',
 'aloe vera juice drink',
 'ambrosia',
 'anchovies, canned in olive oil, with salt, drained',
 'animal fat or drippings',
 'anisette toast',
 'antipasto with ham, fish, cheese, vegetables',
 'apple cider',
 'apple juice beverage, 40-50% juice, light',
 'apple juice, 100%',
 'apple juice, 100%, with calcium added',
 'apple juice, with added vitamin c, from concentrate, shelf stable',
 'apple pie filling',
 'apple salad with dressing',
 'apple, baked',
 'apple, candied',
 'apple, dried',
 'apple, raw',
 'apples, fuji, with skin, raw',
 'apples, fuji, with skin, raw',
 'apples, gala, with skin, raw',
 'apples, gala, with skin, raw',
 'apples, granny smith, with skin, raw',
 'apples, granny smith, with skin, raw',
 'apples, honeycrisp, with skin, raw',
 'apples, honeycrisp, with skin, raw',
 'apples, red delicious, with skin, raw',
 'apples, red delicious, with skin, raw',
 'applesauce, flavored',
 'applesauce, regular',
 'applesauce, unsweetened',
 'applesauce, unsweetened, with added vitamin c',
 'applesauce, unsweetened, with added vitamin c',
 'apricot nectar',
 'apricot, canned',
 'apricot, dried',
 'apricot, raw',
 'apricot, with skin, raw',
 'arepa dominicana',
 'armadillo',
 'artichoke',
 'artichoke dip',
 'artichokes, stuffed',
 'arugula, baby, raw',
 'asian chicken or turkey garden salad with crispy noodles, chicken and/or turkey, lettuce, fruit, nuts, crispy noodles, no dressing',
 'asian chicken or turkey garden salad, chicken and/or turkey, lettuce, fruit, nuts, no dressing',
 'asian stir fry vegetables, cooked, fat added',
 'asian stir fry vegetables, cooked, no added fat',
 'asparagus, canned, cooked with butter or margarine',
 'asparagus, canned, cooked with oil',
 'asparagus, canned, cooked, fat added, ns as to fat type',
 'asparagus, canned, cooked, no added fat',
 'asparagus, fresh, cooked with butter or margarine',
 'asparagus, fresh, cooked with oil',
 'asparagus, fresh, cooked, fat added, ns as to fat type',
 'asparagus, fresh, cooked, no added fat',
 'asparagus, frozen, cooked with butter or margarine',
 'asparagus, frozen, cooked with oil',
 'asparagus, frozen, cooked, fat added, ns as to fat type',
 'asparagus, frozen, cooked, no added fat',
 'asparagus, green, raw',
 'asparagus, ns as to form, cooked',
 'asparagus, raw',
 'atole',
 'atole de avena',
 'atole de chocolate',
 'avocado dressing',
 'avocado, for use on a sandwich',
 'avocado, hass, peeled, raw',
 'avocado, raw',
 'baby toddler apples, stage 1',
 'baby toddler apples, stage 2',
 'baby toddler bananas, stage 1',
 'baby toddler bananas, stage 2',
 'baby toddler bar',
 'baby toddler beef',
 'baby toddler beets',
 'baby toddler biscuit',
 'baby toddler carrots, stage 1',
 'baby toddler carrots, stage 2',
 'baby toddler cereal, barley, dry',
 'baby toddler cereal, multigrain with fruit, dry',
 'baby toddler cereal, multigrain with fruit, ready-to-eat',
 'baby toddler cereal, multigrain, dry',
 'baby toddler cereal, multigrain, ready-to-eat',
 'baby toddler cereal, nfs',
 'baby toddler cereal, oatmeal with fruit, dry',
 'baby toddler cereal, oatmeal with fruit, ready-to-eat',
 'baby toddler cereal, oatmeal, dry',
 'baby toddler cereal, oatmeal, ready-to-eat',
 'baby toddler cereal, rice with fruit, dry',
 'baby toddler cereal, rice with fruit, ready-to-eat',
 'baby toddler cereal, rice, dry',
 'baby toddler cereal, rice, ready-to-eat',
 'baby toddler chicken',
 'baby toddler cookie',
 'baby toddler crackers',
 'baby toddler crunchies',
 'baby toddler food, nfs',
 'baby toddler fruit and meat',
 'baby toddler fruit and vegetables, stage 2',
 'baby toddler fruit and vegetables, stage 3',
 'baby toddler fruit and vegetables, with grain',
 'baby toddler fruit and vegetables, with yogurt',
 'baby toddler fruit, nfs',
 'baby toddler fruit, vegetables, and meat',
 'baby toddler fruit, with grain',
 'baby toddler fruit, with yogurt',
 'baby toddler green beans, stage 1',
 'baby toddler green beans, stage 2',
 'baby toddler ham',
 'baby toddler juice, apple',
 'baby toddler juice, fruit and vegetable',
 'baby toddler juice, fruit and yogurt blend',
 'baby toddler juice, grape',
 'baby toddler juice, mixed fruit',
 'baby toddler juice, nfs',
 'baby toddler juice, pear',
 'baby toddler mangoes',
 'baby toddler meat stick',
 'baby toddler meat, nfs',
 'baby toddler multiple fruit, stage 2',
 'baby toddler multiple fruit, stage 3',
 'baby toddler multiple vegetables, stage 2',
 'baby toddler multiple vegetables, stage 3',
 'baby toddler peaches, stage 1',
 'baby toddler peaches, stage 2',
 'baby toddler pears, stage 1',
 'baby toddler pears, stage 2',
 'baby toddler peas, stage 1',
 'baby toddler peas, stage 2',
 'baby toddler prunes',
 'baby toddler pudding',
 'baby toddler puffs, fruit',
 'baby toddler puffs, vegetable',
 'baby toddler snack, nfs',
 'baby toddler squash, stage 1',
 'baby toddler squash, stage 2',
 'baby toddler sweet potatoes, stage 1',
 'baby toddler sweet potatoes, stage 2',
 'baby toddler turkey',
 'baby toddler vegetable, nfs',
 'baby toddler vegetables and meat',
 'baby toddler vegetables, with grain',
 'baby toddler wheels',
 'baby toddler yogurt melts',
 'baby toddler yogurt, plain',
 'baby toddler yogurt, with fruit',
 'bacalaitos fritos',
 'bacon and tomato dressing',
 'bacon biscuit sandwich',
 'bacon bits',
 'bacon or side pork, fresh, cooked',
 'bacon strip, meatless',
 'bacon, for use on a sandwich',
 'bacon, for use with vegetables',
 'bacon, lettuce, tomato sandwich on wheat',
 'bacon, lettuce, tomato sandwich on white',
 'bacon, ns as to type of meat, cooked',
 'bacon, ns as to type of meat, reduced sodium, cooked',
 'bagel',
 'bagel chips',
 'bagel, multigrain',
 'bagel, multigrain, with raisins',
 'bagel, oat bran',
 'bagel, pumpernickel',
 'bagel, wheat',
 'bagel, wheat bran',
 'bagel, wheat, with fruit and nuts',
 'bagel, wheat, with raisins',
 'bagel, whole grain white',
 'bagel, whole wheat',
 'bagel, whole wheat, with raisins',
 'bagel, with fruit other than raisins',
 'bagel, with raisins',
 'baked beans',
 'baked beans from fast food / restaurant',
 'baked beans, original, canned, with pork',
 'baked beans, reduced sodium',
 'baked beans, vegetarian',
 'baklava',
 'bamboo shoots, cooked',
 'banana chips',
 'banana nectar',
 'banana pudding',
 'banana split',
 'banana, baked',
 'banana, raw',
 'bananas, overripe, raw',
 'bananas, overripe, raw',
 'bananas, ripe and slightly ripe, raw',
 'bananas, ripe and slightly ripe, raw',
 'bao bun',
 'bao bun, no meat',
 'barbecue beef sandwich, on wheat bun',
 'barbecue beef sandwich, on white bun',
 'barbecue beef, no sauce',
 'barbecue beef, with sauce',
 'barbecue chicken',
 'barbecue chicken sandwich, on wheat bun',
 'barbecue chicken sandwich, on white bun',
 'barbecue meat, nfs',
 'barbecue pork sandwich, on wheat bun',
 'barbecue pork sandwich, on white bun',
 'barbecue pork, no sauce',
 'barbecue pork, with sauce',
 'barbecue rib sandwich',
 'barbecue sandwich, nfs',
 'barbecue sauce',
 'barfi or burfi, indian dessert',
 'barley',
 'basbousa',
 'basil, raw',
 'bean cake',
 'bean chips',
 'bean dip, made with refried beans',
 'bean paste, sweetened',
 'bean salad, yellow and/or green string beans',
 'bean sprouts, cooked',
 'bean sprouts, raw',
 'beans and brown rice',
 'beans and franks',
 'beans and rice, from fast food / restaurant',
 'beans and rice, with meat',
 'beans and rice, with tomatoes',
 'beans and tomatoes, fat added',
 'beans and tomatoes, no added fat',
 'beans and white rice',
 'beans with meat, ns as to type',
 'beans, baked, canned, vegetarian',
 'beans, black, canned, sodium added, drained and rinsed',
 'beans, cannellini, canned, sodium added, drained and rinsed',
 'beans, cannellini, dry',
 'beans, dry, black (0% moisture)',
 'beans, dry, black (0% moisture)',
 'beans, dry, brown (0% moisture)',
 'beans, dry, brown (0% moisture)',
 'beans, dry, carioca (0% moisture)',
 'beans, dry, carioca (0% moisture)',
 'beans, dry, cranberry (0% moisture)',
 'beans, dry, cranberry (0% moisture)',
 'beans, dry, dark red kidney (0% moisture)',
 'beans, dry, dark red kidney (0% moisture)',
 'beans, dry, flor de mayo (0% moisture)',
 'beans, dry, flor de mayo (0% moisture)',
 'beans, dry, great northern (0% moisture)',
 'beans, dry, great northern (0% moisture)',
 'beans, dry, light red kidney (0% moisture)',
 'beans, dry, light red kidney (0% moisture)',
 'beans, dry, light tan (0% moisture)',
 'beans, dry, light tan (0% moisture)',
 'beans, dry, medium red (0% moisture)',
 'beans, dry, medium red (0% moisture)',
 'beans, dry, navy (0% moisture)',
 'beans, dry, navy (0% moisture)',
 'beans, dry, pink (0% moisture)',
 'beans, dry, pink (0% moisture)',
 'beans, dry, pinto (0% moisture)',
 'beans, dry, pinto (0% moisture)',
 'beans, dry, red (0% moisture)',
 'beans, dry, red (0% moisture)',
 'beans, dry, small red (0% moisture)',
 'beans, dry, small red (0% moisture)',
 'beans, dry, small white (0% moisture)',
 'beans, dry, small white (0% moisture)',
 'beans, dry, tan (0% moisture)',
 'beans, dry, tan (0% moisture)',
 'beans, from canned, ns as to type, fat added',
 'beans, from canned, ns as to type, no added fat',
 'beans, from dried, ns as to type, fat added',
 'beans, from dried, ns as to type, no added fat',
 'beans, from fast food / restaurant, ns as to type',
 'beans, great northern, canned, sodium added, drained and rinsed',
 'beans, kidney, dark red, canned, sodium added, sugar added, drained and rinsed',
 'beans, kidney, light red, canned, sodium added, sugar added, drained and rinsed',
 'beans, navy, canned, sodium added, drained and rinsed',
 'beans, nfs',
 'beans, pinto, canned, sodium added, drained and rinsed',
 'beans, snap, green, canned, regular pack, drained solids',
 'beans, snap, green, raw',
 'bear',
 'beaver',
 'beef and broccoli',
 'beef and macaroni with cheese sauce',
 'beef and noodles with cream or white sauce',
 'beef and noodles with gravy',
 'beef and noodles with mushroom sauce',
 'beef and noodles with soy-based sauce',
 'beef and noodles with tomato-based sauce',
 'beef and noodles, no sauce',
 'beef and potatoes with cheese sauce',
 'beef and potatoes with cream sauce, white sauce or mushroom sauce',
 'beef and potatoes, no sauce',
 'beef and rice with cheese sauce',
 'beef and rice with cream sauce',
 'beef and rice with gravy',
 'beef and rice with mushroom sauce',
 'beef and rice with soy-based sauce',
 'beef and rice with tomato-based sauce',
 'beef and rice, no sauce',
 'beef and vegetables excluding carrots, broccoli, and dark-green leafy; no potatoes, gravy',
 'beef and vegetables excluding carrots, broccoli, and dark-green leafy; no potatoes, no sauce',
 'beef and vegetables excluding carrots, broccoli, and dark-green leafy; no potatoes, soy-based sauce',
 'beef and vegetables including carrots, broccoli, and/or dark-green leafy; no potatoes, gravy',
 'beef and vegetables including carrots, broccoli, and/or dark-green leafy; no potatoes, no sauce',
 'beef and vegetables including carrots, broccoli, and/or dark-green leafy; no potatoes, soy-based sauce',
 'beef and vegetables, hawaiian style',
 'beef as ingredient in recipes',
 'beef burgundy',
 'beef chow mein or chop suey with noodles',
 'beef chow mein or chop suey, no noodles',
 'beef curry',
 'beef curry with rice',
 'beef dinner, nfs, frozen meal',
 'beef egg foo yung',
 'beef jerky',
 'beef rolls, stuffed with vegetables or meat mixture, tomato-based sauce',
 'beef salad',
 'beef sausage',
 'beef sausage with cheese',
 'beef shish kabob with vegetables, excluding potatoes',
 'beef steak with onions, puerto rican style',
 'beef stew with potatoes, puerto rican style',
 'beef stroganoff',
 'beef stroganoff with noodles',
 'beef taco filling: beef, cheese, tomato, taco sauce',
 'beef wellington',
 'beef with cream or white sauce',
 'beef with gravy',
 'beef with mushroom sauce',
 'beef with soy-based sauce',
 'beef with spaetzle or rice, vegetable, frozen meal',
 'beef with sweet and sour sauce',
 'beef with tomato-based sauce',
 'beef with vegetable, diet frozen meal',
 'beef with vegetables excluding carrots, broccoli, and dark-green leafy; no potatoes, mushroom sauce',
 'beef with vegetables excluding carrots, broccoli, and dark-green leafy; no potatoes, tomato-based sauce',
 'beef with vegetables including carrots, broccoli, and/or dark-green leafy; no potatoes, mushroom sauce',
 'beef with vegetables including carrots, broccoli, and/or dark-green leafy; no potatoes, tomato-based sauce',
 'beef, bacon, cooked',
 'beef, bacon, reduced sodium, cooked',
 'beef, brisket',
 'beef, chuck, roast, boneless, choice, raw',
 'beef, corned',
 'beef, cow head',
 'beef, dried, chipped, cooked in fat',
 'beef, dried, chipped, uncooked',
 'beef, dumplings, and vegetables excluding carrots, broccoli, and dark-green leafy; gravy',
 'beef, dumplings, and vegetables including carrots, broccoli, and/or dark-green leafy; gravy',
 'beef, flank, steak, boneless, choice, raw',
 'beef, for use with vegetables',
 'beef, ground',
 'beef, ground, 80% lean meat / 20% fat, raw',
 'beef, ground, 90% lean meat / 10% fat, raw',
 'beef, ground, patty',
 'beef, ground, raw',
 'beef, ground, with egg and onion',
 'beef, loin, tenderloin roast, separable lean only, boneless, trimmed to 0" fat, select, cooked, roasted',
 'beef, loin, tenderloin roast, separable lean only, boneless, trimmed to 0" fat, select, cooked, roasted',
 'beef, loin, top loin steak, boneless, lip-on, separable lean only, trimmed to 1/8" fat, choice, raw',
 'beef, loin, top loin steak, boneless, lip-on, separable lean only, trimmed to 1/8" fat, choice, raw',
 'beef, neck bones',
 'beef, nfs',
 'beef, noodles, and vegetables excluding carrots, broccoli, and dark-green leafy; gravy',
 'beef, noodles, and vegetables excluding carrots, broccoli, and dark-green leafy; mushroom sauce',
 'beef, noodles, and vegetables excluding carrots, broccoli, and dark-green leafy; no sauce',
 'beef, noodles, and vegetables excluding carrots, broccoli, and dark-green leafy; soy-based sauce',
 'beef, noodles, and vegetables excluding carrots, broccoli, and dark-green leafy; tomato-based sauce',
 'beef, noodles, and vegetables including carrots, broccoli, and/or dark-green leafy; gravy',
 'beef, noodles, and vegetables including carrots, broccoli, and/or dark-green leafy; mushroom sauce',
 'beef, noodles, and vegetables including carrots, broccoli, and/or dark-green leafy; no sauce',
 'beef, noodles, and vegetables including carrots, broccoli, and/or dark-green leafy; soy-based sauce',
 'beef, noodles, and vegetables including carrots, broccoli, and/or dark-green leafy; tomato-based sauce',
 'beef, oxtails',
 'beef, pot roast',
 'beef, potatoes, and vegetables excluding carrots, broccoli, and dark-green leafy; cheese sauce',
 'beef, potatoes, and vegetables excluding carrots, broccoli, and dark-green leafy; cream sauce, white sauce, or mushroom sauce',
 'beef, potatoes, and vegetables excluding carrots, broccoli, and dark-green leafy; gravy',
 'beef, potatoes, and vegetables excluding carrots, broccoli, and dark-green leafy; soy-based sauce',
 'beef, potatoes, and vegetables excluding carrots, broccoli, and dark-green leafy; tomato-based sauce',
 'beef, potatoes, and vegetables including carrots, broccoli, and/or dark-green leafy; cheese sauce',
 'beef, potatoes, and vegetables including carrots, broccoli, and/or dark-green leafy; cream sauce, white sauce, or mushroom sauce',
 'beef, potatoes, and vegetables including carrots, broccoli, and/or dark-green leafy; gravy',
 'beef, potatoes, and vegetables including carrots, broccoli, and/or dark-green leafy; no sauce',
 'beef, potatoes, and vegetables including carrots, broccoli, and/or dark-green leafy; soy-based sauce',
 'beef, potatoes, and vegetables including carrots, broccoli, and/or dark-green leafy; tomato-based sauce',
 'beef, potatoes, and vegetables, excluding carrots, broccoli, and dark-green leafy; no sauce',
 'beef, prepackaged or deli, luncheon meat',
 'beef, prepackaged or deli, luncheon meat, reduced sodium',
 'beef, ribeye, steak, boneless, choice, raw',
 'beef, rice, and vegetables excluding carrots, broccoli, and dark-green leafy; cheese sauce',
 'beef, rice, and vegetables excluding carrots, broccoli, and dark-green leafy; gravy',
 'beef, rice, and vegetables excluding carrots, broccoli, and dark-green leafy; mushroom sauce',
 'beef, rice, and vegetables excluding carrots, broccoli, and dark-green leafy; no sauce',
 'beef, rice, and vegetables excluding carrots, broccoli, and dark-green leafy; soy-based sauce',
 'beef, rice, and vegetables excluding carrots, broccoli, and/or dark-green leafy; tomato-based sauce',
 'beef, rice, and vegetables including carrots, broccoli, and/or dark-green leafy; cheese sauce',
 'beef, rice, and vegetables including carrots, broccoli, and/or dark-green leafy; gravy',
 'beef, rice, and vegetables including carrots, broccoli, and/or dark-green leafy; mushroom sauce',
 'beef, rice, and vegetables including carrots, broccoli, and/or dark-green leafy; no sauce',
 'beef, rice, and vegetables including carrots, broccoli, and/or dark-green leafy; soy-based sauce',
 'beef, rice, and vegetables including carrots, broccoli, and/or dark-green leafy; tomato-based sauce',
 'beef, roast',
 'beef, roast, hash',
 'beef, round, eye of round roast, boneless, separable lean only, trimmed to 0" fat, select, raw',
 'beef, round, eye of round roast, boneless, separable lean only, trimmed to 0" fat, select, raw',
 'beef, round, top round roast, boneless, separable lean only, trimmed to 0" fat, select, raw',
 'beef, round, top round roast, boneless, separable lean only, trimmed to 0" fat, select, raw',
 'beef, round, top round, boneless, choice, raw',
 'beef, sandwich steak',
 'beef, short loin (ny strip steak), raw',
 'beef, short loin, porterhouse steak, separable lean only, trimmed to 1/8" fat, select, raw',
 'beef, short loin, porterhouse steak, separable lean only, trimmed to 1/8" fat, select, raw',
 'beef, short loin, t-bone steak, bone-in, separable lean only, trimmed to 1/8" fat, choice, cooked, grilled',
 'beef, short loin, t-bone steak, bone-in, separable lean only, trimmed to 1/8" fat, choice, cooked, grilled',
 'beef, shortribs',
 'beef, sliced, with gravy, potatoes, vegetable, frozen meal',
 'beef, steak, chuck',
 'beef, steak, country fried',
 'beef, steak, cube',
 'beef, steak, flank',
 'beef, steak, nfs',
 'beef, steak, ribeye, lean and fat eaten',
 'beef, steak, ribeye, lean only eaten',
 'beef, steak, ribeye, ns as to fat eaten',
 'beef, steak, round',
 'beef, steak, sirloin, lean and fat eaten',
 'beef, steak, sirloin, lean only eaten',
 'beef, steak, sirloin, ns as to fat eaten',

In [206]:
ten_whole_foods = ["chicken_wings",
    "apple",
    "banana",
    "beef", # steak, etc
    "carrots",
    "egg", # whole egg
    "strawberries",
    "blueberries",
    "mushrooms",
    "honey"
]

In [207]:
hundred_whole_foods

['apple',
 'banana',
 'blueberries',
 'strawberries',
 'orange',
 'mango',
 'pineapple',
 'watermelon',
 'grapes',
 'pear',
 'peach',
 'kiwi',
 'papaya',
 'avocado',
 'pomegranate',
 'cherries',
 'raspberries',
 'blackberries',
 'cantaloupe',
 'grapefruit',
 'plum',
 'apricot',
 'figs',
 'dates',
 'coconut',
 'carrots',
 'mushrooms',
 'broccoli',
 'cauliflower',
 'cabbage',
 'spinach',
 'lettuce',
 'cucumber',
 'tomato',
 'bell_pepper',
 'onion',
 'garlic',
 'potato',
 'sweet_potato',
 'pumpkin',
 'zucchini',
 'eggplant',
 'asparagus',
 'celery',
 'green_beans',
 'peas',
 'corn',
 'beetroot',
 'radish',
 'turnip',
 'beef',
 'chicken_wings',
 'egg',
 'chicken_breast',
 'chicken_thigh',
 'pork_chop',
 'bacon',
 'turkey_breast',
 'salmon',
 'tuna',
 'shrimp',
 'crab',
 'lobster',
 'squid',
 'cod',
 'sardines',
 'tilapia',
 'lamb_chop',
 'duck_breast',
 'ham',
 'tofu',
 'lentils',
 'chickpeas',
 'kidney_beans',
 'black_beans',
 'peanuts',
 'almonds',
 'cashews',
 'walnuts',
 'pistachios',
 'sunflower_seeds',
 'pumpkin_seeds',
 'sesame_seeds',
 'chia_seeds',
 'soybeans',
 'honey',
 'milk',
 'yogurt',
 'cheddar_cheese',
 'mozzarella_cheese',
 'butter',
 'rice',
 'brown_rice',
 'oats',
 'bread',
 'pasta',
 'noodles',
 'bagel',
 'popcorn',
 'peanut_butter']

## Get ten whole foods `food_id`

Everything except blueberries and honey are available in `foundation_food`. 

For blueberries and honey, we'll have to dig into the survery data: `data_exploration/data/FoodData_Central_survey_food_csv_2020-10-30`

In [208]:
# Get all food ids from foundation_food (honey and blueberries in another dataset)
target_whole_foods = ['apple', # removed chicken wings... can come back later...
 'banana',
 'beef',
 'blueberries',
 'carrots',
 'chicken',
 'egg',
 'honey',
 'strawberries',
 'mushrooms']

target_whole_foods = [

    # =========================
    # FRUITS - 25
    # =========================
    'apple',              # original
    'banana',             # original
    'blueberries',        # original
    'strawberries',       # original
    'orange',
    'mango',
    'pineapple',
    'watermelon',
    'grapes',
    'pear',
    'peach',
    'kiwi',
    'papaya',
    'avocado',
    'pomegranate',
    'cherries',
    'raspberries',
    'blackberries',
    'cantaloupe',
    'grapefruit',
    'plum',
    'apricot',
    'figs',
    'dates',
    'coconut',

    # =========================
    # VEGETABLES - 25
    # =========================
    'carrots',            # original
    'mushrooms',          # original
    'broccoli',
    'cauliflower',
    'cabbage',
    'spinach',
    'lettuce',
    'cucumber',
    'tomato',
    'bell_pepper',
    'onion',
    'garlic',
    'potato',
    'sweet_potato',
    'pumpkin',
    'zucchini',
    'eggplant',
    'asparagus',
    'celery',
    'green_beans',
    'peas',
    'corn',
    'beetroot',
    'radish',
    'turnip',

    # =========================
    # MEAT / SEAFOOD / EGG - 20
    # =========================
    'beef',               # original
    'chicken_wings',      # original
    'egg',                # original
    'chicken_breast',
    'chicken_thigh',
    'pork_chop',
    'bacon',
    'turkey_breast',
    'salmon',
    'tuna',
    'shrimp',
    'crab',
    'lobster',
    'squid',
    'cod',
    'sardines',
    'tilapia',
    'lamb_chop',
    'duck_breast',
    'ham',

    # =========================
    # LEGUMES / NUTS / SEEDS - 15
    # =========================
    'tofu',
    'lentils',
    'chickpeas',
    'kidney_beans',
    'black_beans',
    'peanuts',
    'almonds',
    'cashews',
    'walnuts',
    'pistachios',
    'sunflower_seeds',
    'pumpkin_seeds',
    'sesame_seeds',
    'chia_seeds',
    'soybeans',

    # =========================
    # DAIRY / GRAINS / OTHER - 15
    # =========================
    'honey',              # original
    'milk',
    'yogurt',
    'cheddar_cheese',
    'mozzarella_cheese',
    'butter',
    'rice',
    'brown_rice',
    'oats',
    'bread',
    'pasta',
    'noodles',
    'bagel',
    'popcorn',
    'peanut_butter'
]

In [209]:
len(target_whole_foods)

100

In [229]:
# str.contains can search on regex - https://stackoverflow.com/a/17973255/7900723
pattern = "|".join([f"(?i){food}" for food in target_whole_foods])
pattern

'(?i)apple|(?i)banana|(?i)blueberries|(?i)strawberries|(?i)orange|(?i)mango|(?i)pineapple|(?i)watermelon|(?i)grapes|(?i)pear|(?i)peach|(?i)kiwi|(?i)papaya|(?i)avocado|(?i)pomegranate|(?i)cherries|(?i)raspberries|(?i)blackberries|(?i)cantaloupe|(?i)grapefruit|(?i)plum|(?i)apricot|(?i)figs|(?i)dates|(?i)coconut|(?i)carrots|(?i)mushrooms|(?i)broccoli|(?i)cauliflower|(?i)cabbage|(?i)spinach|(?i)lettuce|(?i)cucumber|(?i)tomato|(?i)bell_pepper|(?i)onion|(?i)garlic|(?i)potato|(?i)sweet_potato|(?i)pumpkin|(?i)zucchini|(?i)eggplant|(?i)asparagus|(?i)celery|(?i)green_beans|(?i)peas|(?i)corn|(?i)beetroot|(?i)radish|(?i)turnip|(?i)beef|(?i)chicken_wings|(?i)egg|(?i)chicken_breast|(?i)chicken_thigh|(?i)pork_chop|(?i)bacon|(?i)turkey_breast|(?i)salmon|(?i)tuna|(?i)shrimp|(?i)crab|(?i)lobster|(?i)squid|(?i)cod|(?i)sardines|(?i)tilapia|(?i)lamb_chop|(?i)duck_breast|(?i)ham|(?i)tofu|(?i)lentils|(?i)chickpeas|(?i)kidney_beans|(?i)black_beans|(?i)peanuts|(?i)almonds|(?i)cashews|(?i)walnuts|(?i)pistachios|(?i)sunflower_seeds|(?i)pumpkin_seeds|(?i)sesame_seeds|(?i)chia_seeds|(?i)soybeans|(?i)honey|(?i)milk|(?i)yogurt|(?i)cheddar_cheese|(?i)mozzarella_cheese|(?i)butter|(?i)rice|(?i)brown_rice|(?i)oats|(?i)bread|(?i)pasta|(?i)noodles|(?i)bagel|(?i)popcorn|(?i)peanut_butter'

In [ ]:
foundation_food[foundation_food["description"].str.contains(pattern, case=False)].sort_values(by=["description"])

In [234]:
foundation_food[foundation_food["description"].str.contains("honey")]

,fdc_id,data_type,description,food_category_id,publication_date
20191,1105547,foundation_food,"apples, honeycrisp, with skin, raw",9.0,2020-10-30
20547,1750343,foundation_food,"apples, honeycrisp, with skin, raw",9.0,2020-10-30
63976,2710816,foundation_food,"melons, honeydew, raw",9.0,2024-10-31
90098,2707491,survey_fndds_food,"almonds, honey roasted",2804.0,2022-10-28
90105,2707498,survey_fndds_food,"cashews, honey roasted",2804.0,2022-10-28
90118,2707511,survey_fndds_food,"mixed nuts, honey roasted",2804.0,2022-10-28
90127,2707520,survey_fndds_food,"peanuts, honey roasted",2804.0,2022-10-28
90132,2707525,survey_fndds_food,"pecans, honey roasted",2804.0,2022-10-28
90138,2707531,survey_fndds_food,"walnuts, excluding honey roasted",2804.0,2022-10-28
90139,2707532,survey_fndds_food,"walnuts, honey roasted",2804.0,2022-10-28
90641,2708034,survey_fndds_food,"sopaipilla, without syrup or honey",5506.0,2022-10-28
90642,2708035,survey_fndds_food,sopaipilla with syrup or honey,5506.0,2022-10-28
91024,2708417,survey_fndds_food,"rice, sweet, cooked with honey",4002.0,2022-10-28
91071,2708464,survey_fndds_food,"cereal, o's, honey nut",4602.0,2022-10-28
91093,2708486,survey_fndds_food,"cereal, other, honey",4602.0,2022-10-28
91848,2709241,survey_fndds_food,"honeydew melon, raw",6014.0,2022-10-28
92693,2710086,survey_fndds_food,honey mustard dip,8406.0,2022-10-28
92786,2710179,survey_fndds_food,honey butter,8002.0,2022-10-28
92809,2710202,survey_fndds_food,honey mustard dressing,8012.0,2022-10-28
92830,2710223,survey_fndds_food,"honey mustard dressing, light",8012.0,2022-10-28
92840,2710233,survey_fndds_food,"honey mustard dressing, fat free",8012.0,2022-10-28
92888,2710281,survey_fndds_food,honey,8802.0,2022-10-28

In [216]:
# Found this earlier
chicken_wing_id

331897

In [237]:
# Build a mapping: for each food, find the best fdc_id match
import pandas as pd

food_id_map = {}

for food_name in target_whole_foods:
    matches = food[food["description"].str.contains(
        food_name.replace("_", " "), case=False, na=False
    )][["fdc_id", "description", "data_type"]].copy()
    
    if len(matches) == 0:
        print(f"❌ {food_name:20s} → NO MATCH FOUND")
        continue
    
    priority = {"foundation_food": 1, "survey_fndds_food": 2}
    matches["priority"] = matches["data_type"].map(priority).fillna(3)
    matches = matches.sort_values("priority")
    
    top5 = matches.head(5)
    print(f"\n{'='*60}")
    print(f"🍽 {food_name} — top {len(top5)} matches:")
    for _, row in top5.iterrows():
        print(f"   ID: {row['fdc_id']:>8}  |  {row['description']:50s}  ({row['data_type']})")
    
    best = matches.iloc[0]
    food_id_map[food_name] = int(best["fdc_id"])

print(f"\n{'='*60}")
print(f"\nSummary: found IDs for {len(food_id_map)} / {len(target_whole_foods)} foods")

============================================================
🍽 apple — top 5 matches:
   ID:  1750342  |  apples, granny smith, with skin, raw                (foundation_food)
   ID:  1750343  |  apples, honeycrisp, with skin, raw                  (foundation_food)
   ID:  1105430  |  apples, red delicious, with skin, raw               (foundation_food)
   ID:  1105547  |  apples, honeycrisp, with skin, raw                  (foundation_food)
   ID:  1750339  |  apples, red delicious, with skin, raw               (foundation_food)

============================================================
🍽 banana — top 5 matches:
   ID:  2747660  |  peppers, banana or hungarian wax, seeded, raw       (foundation_food)
   ID:  1105073  |  bananas, overripe, raw                              (foundation_food)
   ID:  1105314  |  bananas, ripe and slightly ripe, raw                (foundation_food)
   ID:   790991  |  bananas, ripe and slightly ripe, raw                (foundation_food)
   ID:   790774  |  bananas, overripe, raw                              (foundation_food)

============================================================
🍽 blueberries — top 5 matches:
   ID:  2263889  |  blueberries, raw                                    (foundation_food)
   ID:  2346411  |  blueberries, raw                                    (foundation_food)
   ID:  2709277  |  blueberries, frozen                                 (survey_fndds_food)
   ID:  2709275  |  blueberries, raw                                    (survey_fndds_food)
   ID:  2709198  |  blueberries, dried                                  (survey_fndds_food)

============================================================
🍽 strawberries — top 5 matches:
   ID:  2346409  |  strawberries, raw                                   (foundation_food)
   ID:  2263887  |  strawberries, raw                                   (foundation_food)
   ID:   747448  |  strawberries, raw                                   (foundation_food)
   ID:   327699  |  strawberries, raw                                   (foundation_food)
   ID:  2709283  |  strawberries, raw                                   (survey_fndds_food)

============================================================
🍽 orange — top 5 matches:
   ID:  2346404  |  sweet potatoes, orange flesh, without skin, raw     (foundation_food)
   ID:  2258591  |  peppers, bell, orange, raw                          (foundation_food)
   ID:   746771  |  oranges, raw, navels                                (foundation_food)
   ID:  2003591  |  orange juice, no pulp, not fortified, from concentrate, refrigerated  (foundation_food)
   ID:  2003597  |  orange juice, no pulp, not fortified, not from concentrate, refrigerated  (foundation_food)

============================================================
🍽 mango — top 5 matches:
   ID:  2710833  |  mango, tommy atkins, peeled, raw                    (foundation_food)
   ID:  2710834  |  mango, ataulfo, peeled, raw                         (foundation_food)
   ID:  2709372  |  baby toddler mangoes                                (survey_fndds_food)
   ID:  2709345  |  mango nectar                                        (survey_fndds_food)
   ID:  2709244  |  mango, frozen                                       (survey_fndds_food)

============================================================
🍽 pineapple — top 5 matches:
   ID:  2346398  |  pineapple, raw                                      (foundation_food)
   ID:  2709261  |  pineapple, canned, nfs                              (survey_fndds_food)
   ID:  2708010  |  pie, pineapple cream                                (survey_fndds_food)
   ID:  2707890  |  cake, pineapple, upside down                        (survey_fndds_food)
   ID:  2709264  |  pineapple, frozen                                   (survey_fndds_food)

============================================================
🍽 watermelon — top 5 matches:
   ID:  2747675  |  watermelon, seedless, flesh only, raw               (foundation_food)
   ID:  2747676  |  watermelon, seedless, rind only, raw                (foundation_food)
   ID:  2709333  |  watermelon juice, 100%                              (survey_fndds_food)
   ID:  2709270  |  watermelon, raw                                     (survey_fndds_food)
   ID:  2757920  |  watermelon, seedless, rind only, raw                (sub_sample_food)

============================================================
🍽 grapes — top 5 matches:
   ID:  2263890  |  grapes, red, seedless, raw                          (foundation_food)
   ID:  2263891  |  grapes, green, seedless, raw                        (foundation_food)
   ID:  2346413  |  grapes, green, seedless, raw                        (foundation_food)
   ID:  2346412  |  grapes, red, seedless, raw                          (foundation_food)
   ID:  2709237  |  grapes, raw                                         (survey_fndds_food)

============================================================
🍽 pear — top 5 matches:
   ID:   746773  |  pears, raw, bartlett                                (foundation_food)
   ID:   332597  |  pears, raw, bartlett (includes foods for usda's food distribution program)  (foundation_food)
   ID:  2710841  |  sorghum grain, white, pearled, unenriched, dry, raw  (foundation_food)
   ID:  2710840  |  sorghum flour, white, pearled, unenriched, dry, raw  (foundation_food)
   ID:  2710836  |  pear, anjou, green, with skin, raw                  (foundation_food)

============================================================
🍽 peach — top 5 matches:
   ID:   325430  |  peaches, yellow, raw                                (foundation_food)
   ID:  2709253  |  peach, frozen                                       (survey_fndds_food)
   ID:  2708043  |  strudel, peach                                      (survey_fndds_food)
   ID:  2709346  |  peach nectar                                        (survey_fndds_food)
   ID:  2708022  |  cobbler, peach                                      (survey_fndds_food)

============================================================
🍽 kiwi — top 5 matches:
   ID:   327046  |  kiwifruit, green, raw                               (foundation_food)
   ID:  2710831  |  kiwifruit (kiwi), green, peeled, raw                (foundation_food)
   ID:  2709239  |  kiwi fruit, raw                                     (survey_fndds_food)
   ID:  2714461  |  kiwifruit (kiwi), green, peeled, raw                (sub_sample_food)
   ID:  2714460  |  kiwifruit (kiwi), green, peeled, raw                (sub_sample_food)

============================================================
🍽 papaya — top 5 matches:
   ID:  2709206  |  papaya, dried                                       (survey_fndds_food)
   ID:  2709246  |  papaya, raw                                         (survey_fndds_food)
   ID:  2709247  |  papaya, canned                                      (survey_fndds_food)
   ID:  2709327  |  papaya juice, 100%                                  (survey_fndds_food)
   ID:  2709347  |  papaya nectar                                       (survey_fndds_food)

============================================================
🍽 avocado — top 5 matches:
   ID:  2710824  |  avocado, hass, peeled, raw                          (foundation_food)
   ID:  2709223  |  avocado, raw                                        (survey_fndds_food)
   ID:  2709824  |  lettuce, salad with avocado, tomato, and/or carrots, with or without other vegetables, no dressing  (survey_fndds_food)
   ID:  2708960  |  sushi roll, avocado                                 (survey_fndds_food)
   ID:  2710248  |  avocado, for use on a sandwich                      (survey_fndds_food)

============================================================
🍽 pomegranate — top 5 matches:
   ID:  2727588  |  juice, pomegranate, from concentrate, shelf-stable  (foundation_food)
   ID:  2709330  |  pomegranate juice, 100%                             (survey_fndds_food)
   ID:  2709267  |  pomegranate, raw                                    (survey_fndds_food)
   ID:  2710593  |  pomegranate juice beverage, 40-50% juice, light     (survey_fndds_food)
   ID:  2727821  |  juice, pomegranate, from concentrate, shelf-stable  (sample_food)

============================================================
🍽 cherries — top 5 matches:
   ID:  2346399  |  cherries, sweet, dark red, raw                      (foundation_food)
   ID:  2709231  |  cherries, raw                                       (survey_fndds_food)
   ID:  2709229  |  cherries, maraschino                                (survey_fndds_food)
   ID:  2709232  |  cherries, canned                                    (survey_fndds_food)
   ID:  2709199  |  cherries, dried                                     (survey_fndds_food)

============================================================
🍽 raspberries — top 5 matches:
   ID:  2263888  |  raspberries, raw                                    (foundation_food)
   ID:  2346410  |  raspberries, raw                                    (foundation_food)
   ID:  2709282  |  raspberries, frozen                                 (survey_fndds_food)
   ID:  2709281  |  raspberries, raw                                    (survey_fndds_food)
   ID:  2352856  |  raspberries, fresh, raw                             (sub_sample_food)

============================================================
🍽 blackberries — top 5 matches:
   ID:  2727581  |  blackberries, raw                                   (foundation_food)
   ID:  2709273  |  blackberries, raw                                   (survey_fndds_food)
   ID:  2709274  |  blackberries, frozen                                (survey_fndds_food)
   ID:  2727831  |  blackberries, raw                                   (sample_food)
   ID:  2727837  |  blackberries, raw                                   (sample_food)

============================================================
🍽 cantaloupe — top 5 matches:
   ID:   327198  |  melons, cantaloupe, raw                             (foundation_food)
   ID:   746770  |  melons, cantaloupe, raw                             (foundation_food)
   ID:  2709226  |  cantaloupe, raw                                     (survey_fndds_food)
   ID:  2709343  |  cantaloupe nectar                                   (survey_fndds_food)
   ID:   327047  |  cantaloupe, raw, region 2, c0009h, pure composite   (sample_food)

============================================================
🍽 grapefruit — top 5 matches:
   ID:  2758977  |  grapefruit, raw                                     (foundation_food)
   ID:   325287  |  grapefruit juice, white, canned or bottled, unsweetened  (foundation_food)
   ID:  2003595  |  grapefruit juice, red, not fortified, not from concentrate, refrigerated  (foundation_food)
   ID:  2709179  |  grapefruit juice, 100%, with calcium added          (survey_fndds_food)
   ID:  2709165  |  grapefruit, raw                                     (survey_fndds_food)

============================================================
🍽 plum — top 5 matches:
   ID:  2710837  |  plum, black, with skin, raw                         (foundation_food)
   ID:  2758978  |  plums, dried (prunes), uncooked                     (foundation_food)
   ID:  2709266  |  plum, canned                                        (survey_fndds_food)
   ID:  2709265  |  plum, raw                                           (survey_fndds_food)
   ID:  2759715  |  plums, dried (prunes), uncooked                     (sub_sample_food)

============================================================
🍽 apricot — top 5 matches:
   ID:  2710815  |  apricot, with skin, raw                             (foundation_food)
   ID:  2709221  |  apricot, raw                                        (survey_fndds_food)
   ID:  2709222  |  apricot, canned                                     (survey_fndds_food)
   ID:  2709341  |  apricot nectar                                      (survey_fndds_food)
   ID:  2709197  |  apricot, dried                                      (survey_fndds_food)

============================================================
🍽 figs — top 5 matches:
   ID:   746768  |  figs, dried, uncooked                               (foundation_food)
   ID:   326905  |  figs, dried, uncooked                               (foundation_food)
   ID:   326699  |  figs, mission, dried, region 3, pure composite, cy0100s  (sample_food)
   ID:   326700  |  mission figs, dried, region 3, il2, nfy010145       (market_acquisition)
   ID:   326703  |  mission figs, dried, region 3, il2, nfy010148       (market_acquisition)
❌ dates                → NO MATCH FOUND

============================================================
🍽 coconut — top 5 matches:
   ID:  2515382  |  flour, coconut                                      (foundation_food)
   ID:   330458  |  oil, coconut                                        (foundation_food)
   ID:  2707501  |  coconut, packaged                                   (survey_fndds_food)
   ID:  2707568  |  coconut milk, used in cooking                       (survey_fndds_food)
   ID:  2709032  |  rice, cooked with coconut milk                      (survey_fndds_food)

============================================================
🍽 carrots — top 5 matches:
   ID:   326458  |  carrots, frozen, unprepared (includes foods for usda's food distribution program)  (foundation_food)
   ID:  2258587  |  carrots, baby, raw                                  (foundation_food)
   ID:  2258586  |  carrots, mature, raw                                (foundation_food)
   ID:   746764  |  carrots, frozen, unprepared                         (foundation_food)
   ID:  2710793  |  carrots, cooked, as ingredient                      (survey_fndds_food)

============================================================
🍽 mushrooms — top 5 matches:
   ID:  1750346  |  mushrooms, shiitake                                 (foundation_food)
   ID:  1999628  |  mushrooms, shiitake                                 (foundation_food)
   ID:  1999629  |  mushrooms, white button                             (foundation_food)
   ID:  1750347  |  mushrooms, white button                             (foundation_food)
   ID:  2709793  |  mushrooms, raw                                      (survey_fndds_food)

============================================================
🍽 broccoli — top 5 matches:
   ID:   747447  |  broccoli, raw                                       (foundation_food)
   ID:   321900  |  broccoli, raw                                       (foundation_food)
   ID:  2710792  |  broccoli, cooked, as ingredient                     (survey_fndds_food)
   ID:  2710034  |  broccoli, cauliflower and carrots, cooked, fat added  (survey_fndds_food)
   ID:  2706859  |  shellfish mixture and vegetables including carrots, broccoli, and/or dark-green leafy; no potatoes, soy-based sauce  (survey_fndds_food)

============================================================
🍽 cauliflower — top 5 matches:
   ID:  2685573  |  cauliflower, raw                                    (foundation_food)
   ID:  2709903  |  cauliflower, fresh, cooked with butter or margarine  (survey_fndds_food)
   ID:  2709904  |  cauliflower, frozen, cooked with oil                (survey_fndds_food)
   ID:  2709905  |  cauliflower, frozen, cooked with butter or margarine  (survey_fndds_food)
   ID:  2710031  |  broccoli and cauliflower, cooked, no added fat      (survey_fndds_food)

============================================================
🍽 cabbage — top 5 matches:
   ID:  2346407  |  cabbage, green, raw                                 (foundation_food)
   ID:  2346408  |  cabbage, red, raw                                   (foundation_food)
   ID:  2727583  |  cabbage, napa, leaf, destemmed, raw                 (foundation_food)
   ID:  2685572  |  cabbage, bok choy, raw                              (foundation_food)
   ID:  2710143  |  stuffed cabbage, with meat and rice, syrian dish, puerto rican style  (survey_fndds_food)

============================================================
🍽 spinach — top 5 matches:
   ID:  1750352  |  spinach, baby                                       (foundation_food)
   ID:  1750353  |  spinach, mature                                     (foundation_food)
   ID:  1999632  |  spinach, baby                                       (foundation_food)
   ID:  1999633  |  spinach, mature                                     (foundation_food)
   ID:  2709831  |  spinach salad, no dressing                          (survey_fndds_food)

============================================================
🍽 lettuce — top 5 matches:
   ID:  2346390  |  lettuce, leaf, red, raw                             (foundation_food)
   ID:  2346388  |  lettuce, iceberg, raw                               (foundation_food)
   ID:  2346389  |  lettuce, romaine, green, raw                        (foundation_food)
   ID:  2346391  |  lettuce, leaf, green, raw                           (foundation_food)
   ID:   327923  |  lettuce, cos or romaine, raw                        (foundation_food)

============================================================
🍽 cucumber — top 5 matches:
   ID:   324653  |  pickles, cucumber, dill or kosher dill              (foundation_food)
   ID:  2346406  |  cucumber, with peel, raw                            (foundation_food)
   ID:  2709819  |  cucumber salad, made with sour cream dressing       (survey_fndds_food)
   ID:  2709818  |  cucumber and vegetable namasu                       (survey_fndds_food)
   ID:  2709820  |  cucumber salad, made with italian dressing          (survey_fndds_food)

============================================================
🍽 tomato — top 5 matches:
   ID:  2685582  |  tomato, puree, canned                               (foundation_food)
   ID:  2685578  |  tomatoes, whole, canned, solids and liquids, with salt added  (foundation_food)
   ID:  2685579  |  tomato, sauce, canned, with salt added              (foundation_food)
   ID:  2685580  |  tomato, paste, canned, without salt added           (foundation_food)
   ID:  2685581  |  tomatoes, crushed, canned                           (foundation_food)
❌ bell_pepper          → NO MATCH FOUND

============================================================
🍽 onion — top 5 matches:
   ID:  1104962  |  onions, white, raw                                  (foundation_food)
   ID:  2727585  |  green onion, (scallion), bulb and greens, root removed, raw  (foundation_food)
   ID:   790646  |  onions, yellow, raw                                 (foundation_food)
   ID:   790577  |  onions, red, raw                                    (foundation_food)
   ID:   324317  |  onion rings, breaded, par fried, frozen, prepared, heated in oven  (foundation_food)

============================================================
🍽 garlic — top 5 matches:
   ID:  1104647  |  garlic, raw                                         (foundation_food)
   ID:  2707629  |  garlic bread, with parmesan cheese, from fast food / restaurant  (survey_fndds_food)
   ID:  2707631  |  garlic bread, with melted cheese, from fast food / restaurant  (survey_fndds_food)
   ID:  2707662  |  roll, garlic                                        (survey_fndds_food)
   ID:  2707627  |  garlic bread, from fast food / restaurant           (survey_fndds_food)

============================================================
🍽 potato — top 5 matches:
   ID:  2261422  |  flour, potato                                       (foundation_food)
   ID:  2346401  |  potatoes, russet, without skin, raw                 (foundation_food)
   ID:  2346402  |  potatoes, red, without skin, raw                    (foundation_food)
   ID:  2346403  |  potatoes, gold, without skin, raw                   (foundation_food)
   ID:  2346404  |  sweet potatoes, orange flesh, without skin, raw     (foundation_food)


In [241]:
# Broader searches for the 4 missing
broad = {
    "turkey_breast": "turkey",
    "lamb_chop": "lamb",
    "duck_breast": "duck",
    "dates": "date",
}
for name, term in broad.items():
    matches = food[food["description"].str.contains(rf"\b{term}\b", case=False, na=False, regex=True)][
        ["fdc_id", "description", "data_type"]
    ].head(3)
    print(f"\n--- {name} (searched: '{term}') ---")
    if len(matches) == 0:
        print("  ❌ NO MATCH")
    for _, row in matches.iterrows():
        print(f"  ID: {row['fdc_id']:>8} | {row['description']:55s} | {row['data_type']}")

--- turkey_breast (searched: 'turkey') ---
  ID:   325872 | turkey breakfast sausage, honeysuckle white             | sample_food
  ID:   325873 | turkey breakfast sausage, honeysuckle white             | market_acquisition
  ID:   325874 | turkey breakfast sausage, honeysuckle white             | market_acquisition

--- lamb_chop (searched: 'lamb') ---
  ID:  2727570 | lamb, ground, raw                                       | foundation_food
  ID:  2727651 | lamb, ground, raw                                       | sample_food
  ID:  2727653 | lamb, ground, raw                                       | sample_food

--- duck_breast (searched: 'duck') ---
  ID:  2706137 | duck, cooked, skin eaten                                | survey_fndds_food
  ID:  2706138 | duck, cooked, skin not eaten                            | survey_fndds_food
  ID:  2706139 | duck, roasted, skin eaten                               | survey_fndds_food

--- dates (searched: 'date') ---
  ID:  2708115 | breakfast bar, date, with yogurt coating                | survey_fndds_food
  ID:  2709203 | date                                                    | survey_fndds_food

In [242]:
# Map foods to food_id (these have been filtered from larger quantities to smaller quantities)
# For example, if there were 5 kinds of apple, only one was chosen
whole_foods_id_map = {1750339: "apple", # red delicious
    1105314: "banana", # Bananas, ripe and slightly ripe, raw
    1102702: "blueberries", # blueberries, raw	
    746763: "beef", # t-bone steak 
    746764: "carrots", # frozen unprepared
    331897: "chicken_wings", # Chicken, broilers or fryers, drumstick, meat o...	
    329490: "egg", # Egg, whole, dried	
    1103956: "honey", # Honey
    1750347: "mushrooms", # Mushrooms, white button
    747448: "strawberries" # strawberries, raw
}
whole_foods_id_map = {
    # =========================
    # FRUITS - 25
    # =========================
    1750339: "apple",           # apples, red delicious, with skin, raw
    1105314: "banana",          # bananas, ripe and slightly ripe, raw
    2263889: "blueberries",     # blueberries, raw
    2346409: "strawberries",    # strawberries, raw
    746771: "orange",           # oranges, raw, navels
    2710833: "mango",           # mango, tommy atkins, peeled, raw
    2346398: "pineapple",       # pineapple, raw
    2747675: "watermelon",      # watermelon, seedless, flesh only, raw
    2263890: "grapes",          # grapes, red, seedless, raw
    746773: "pear",             # pears, raw, bartlett
    325430: "peach",            # peaches, yellow, raw
    327046: "kiwi",             # kiwifruit, green, raw
    2709246: "papaya",          # papaya, raw
    2710824: "avocado",         # avocado, hass, peeled, raw
    2709267: "pomegranate",     # pomegranate, raw
    2346399: "cherries",        # cherries, sweet, dark red, raw
    2263888: "raspberries",     # raspberries, raw
    2727581: "blackberries",    # blackberries, raw
    327198: "cantaloupe",       # melons, cantaloupe, raw
    2758977: "grapefruit",      # grapefruit, raw
    2710837: "plum",            # plum, black, with skin, raw
    2710815: "apricot",         # apricot, with skin, raw
    746768: "figs",             # figs, dried, uncooked
    2709203: "dates",           # date
    2707501: "coconut",         # coconut, packaged

    # =========================
    # VEGETABLES - 25
    # =========================
    746764: "carrots",          # carrots, frozen, unprepared
    1750347: "mushrooms",       # mushrooms, white button
    747447: "broccoli",         # broccoli, raw
    2685573: "cauliflower",     # cauliflower, raw
    2346407: "cabbage",         # cabbage, green, raw
    1750352: "spinach",         # spinach, baby
    2346388: "lettuce",         # lettuce, iceberg, raw
    2346406: "cucumber",        # cucumber, with peel, raw
    2685578: "tomato",          # tomatoes, whole, canned
    2258588: "bell_pepper",     # peppers, bell, green, raw
    1104962: "onion",           # onions, white, raw
    1104647: "garlic",          # garlic, raw
    2346401: "potato",          # potatoes, russet, without skin, raw
    2346404: "sweet_potato",    # sweet potatoes, orange flesh, without skin, raw
    2727578: "pumpkin",         # squash, pie pumpkin, peeled, seeded, raw
    2685568: "zucchini",        # squash, summer, green, zucchini, raw
    2685577: "eggplant",        # eggplant, raw
    2710823: "asparagus",       # asparagus, green, raw
    2346405: "celery",          # celery, raw
    2709853: "green_beans",     # green beans, frozen, cooked, no added fat
    2644291: "peas",            # peas, green, sweet, canned
    2710826: "corn",            # corn, sweet, yellow and white kernels, fresh, raw
    2685576: "beetroot",        # beets, raw
    2747665: "radish",          # radishes, red, raw
    2747674: "turnip",          # turnips, raw

    # =========================
    # MEAT / SEAFOOD / EGG - 20
    # =========================
    746763: "beef",             # beef, t-bone steak
    331897: "chicken_wings",    # chicken, broilers or fryers, drumstick, meat only
    329490: "egg",              # egg, whole, dried
    2759004: "chicken_breast",  # lunchmeat, chicken breast, sliced
    2706027: "chicken_thigh",   # chicken thigh, ns as to cooking method, skin eaten
    2646168: "pork_chop",       # pork, loin, boneless, raw
    749420: "bacon",            # pork, cured, bacon, cooked, restaurant
    2514747: "turkey_breast",   # turkey, ground, 93% lean/7% fat, raw
    2684440: "salmon",          # fish, salmon, sockeye, wild caught, raw
    2747673: "tuna",            # tuna, ahi or yellowfin, frozen, wild caught
    2684443: "shrimp",          # crustaceans, shrimp, farm raised, raw
    2684446: "crab",            # crustaceans, crab, blue swimming, lump, pasteurized
    2747657: "lobster",         # lobster, tail only, frozen, wild caught
    2747671: "squid",           # squid (calamari), frozen, tubes only
    2684444: "cod",             # fish, cod, atlantic, wild caught, raw
    2706293: "sardines",        # fish, sardines, canned
    2684442: "tilapia",         # fish, tilapia, farm raised, raw
    2727570: "lamb_chop",       # lamb, ground, raw
    2706137: "duck_breast",     # duck, cooked, skin eaten
    2759002: "ham",             # lunchmeat, ham, black forest, sliced

    # =========================
    # LEGUMES / NUTS / SEEDS - 15
    # =========================
    # tofu → not in dataset; use a substitute
    2644283: "Lentils, dry",            # PLACEHOLDER: currently lentils. Search for "soybean curd" or replace
    2644283: "lentils",         # lentils, dry
    2644282: "chickpeas",       # chickpeas, (garbanzo beans, bengal gram), dry
    2707379: "kidney_beans",    # kidney beans, nfs
    2707359: "black_beans",     # black beans, nfs
    2515376: "peanuts",         # peanuts, raw
    2346393: "almonds",         # nuts, almonds, whole, raw
    2707497: "cashews",         # cashews, unsalted
    2346394: "walnuts",         # nuts, walnuts, english, halves, raw
    2515379: "pistachios",      # nuts, pistachio nuts, raw
    2707585: "sunflower_seeds", # sunflower seeds, nfs
    2515380: "pumpkin_seeds",   # seeds, pumpkin seeds (pepitas), raw
    2707586: "sesame_seeds",    # sesame seeds
    2710819: "chia_seeds",      # chia seeds, dry, raw
    2707388: "soybeans",        # soybeans, cooked

    # =========================
    # DAIRY / GRAINS / OTHER - 15
    # =========================
    2710281: "honey",           # honey
    746782: "milk",             # milk, whole, 3.25% milkfat
    2259793: "yogurt",          # yogurt, plain, whole milk
    325198: "cheddar_cheese",   # cheese, pasteurized process, american
    # mozzarella → not in dataset; use provolone as closest
    2647440: "Cheese, provolone, sliced", # cheese, provolone, sliced
    790508: "butter",           # butter, stick, salted
    2512381: "rice",            # rice, white, long grain, unenriched, raw
    2709033: "brown_rice",      # beans and brown rice
    2346396: "oats",            # oats, whole grain, rolled, old fashioned
    335240: "bread",            # bread, whole-wheat, commercially prepared
    2758998: "pasta",           # pasta, dry, enriched, spaghetti
    2706480: "noodles",         # beef and noodles, no sauce
    2707684: "bagel",           # bagel
    2708216: "popcorn",         # popcorn, nfs
    324860: "peanut_butter",    # peanut butter, smooth style, with salt
}

In [244]:
len(target_whole_foods)

100

In [245]:
# Find nutrition for eight whole foods
target_whole_foods_df = food_nutrient[(food_nutrient["fdc_id"].isin(list(whole_foods_id_map.keys()))) & \
    (food_nutrient["nutrient_id"].isin(list(target_nutrient_dict.keys())))][["fdc_id", "nutrient_id", "amount"]]
target_whole_foods_df

         fdc_id  nutrient_id  amount
16925    324860         1003   22.50
16943    324860         1005   22.30
16950    324860         1004   51.10
16980    324860         1008  597.00
16991    324860         2048  597.00
...         ...          ...     ...
461005  2709853          204    0.17
488776  2710281          203    0.30
488795  2710281          205   82.40
488829  2710281          204    0.00
488833  2710281          208  304.00

[380 rows x 3 columns]

In [246]:
# Pivot the table to how we want it
target_whole_foods_df = target_whole_foods_df.pivot_table("amount", "fdc_id", "nutrient_id")
target_whole_foods_df

nutrient_id,203,204,205,208,1003,1004,1005,1008,2048
fdc_id,,,,,,,,,
324860,NaN,NaN,NaN,NaN,22.500000,51.10000,22.300000,597.0,597.0
325198,NaN,NaN,NaN,NaN,18.000000,30.60000,5.270000,366.0,366.0
325430,NaN,NaN,NaN,NaN,0.910000,0.27000,10.100000,42.0,42.0
327046,NaN,NaN,NaN,NaN,1.060000,0.44000,14.000000,58.0,58.0
327198,NaN,NaN,NaN,NaN,0.820000,0.18000,8.160000,34.0,NaN
...,...,...,...,...,...,...,...,...,...
2747665,NaN,NaN,NaN,NaN,0.656250,0.08313,4.056820,NaN,NaN
2747671,NaN,NaN,NaN,NaN,8.806250,0.55080,0.932150,NaN,NaN
2747673,NaN,NaN,NaN,NaN,24.700000,0.38750,-0.104500,NaN,NaN
2747674,NaN,NaN,NaN,NaN,0.953125,0.11880,7.274975,NaN,NaN
2747675,NaN,NaN,NaN,NaN,0.871250,NaN,NaN,NaN,NaN

In [247]:
target_whole_foods_df.columns

Index([203, 204, 205, 208, 1003, 1004, 1005, 1008, 2048], dtype='int64', name='nutrient_id')

In [248]:
len(whole_foods_id_map)

99

In [249]:
target_whole_foods_df = target_whole_foods_df.reset_index(drop=False).rename_axis(None, axis=1)
target_whole_foods_df

     fdc_id  203  204  205  208       1003      1004       1005   1008   2048
0    324860  NaN  NaN  NaN  NaN  22.500000  51.10000  22.300000  597.0  597.0
1    325198  NaN  NaN  NaN  NaN  18.000000  30.60000   5.270000  366.0  366.0
2    325430  NaN  NaN  NaN  NaN   0.910000   0.27000  10.100000   42.0   42.0
3    327046  NaN  NaN  NaN  NaN   1.060000   0.44000  14.000000   58.0   58.0
4    327198  NaN  NaN  NaN  NaN   0.820000   0.18000   8.160000   34.0    NaN
..      ...  ...  ...  ...  ...        ...       ...        ...    ...    ...
90  2747665  NaN  NaN  NaN  NaN   0.656250   0.08313   4.056820    NaN    NaN
91  2747671  NaN  NaN  NaN  NaN   8.806250   0.55080   0.932150    NaN    NaN
92  2747673  NaN  NaN  NaN  NaN  24.700000   0.38750  -0.104500    NaN    NaN
93  2747674  NaN  NaN  NaN  NaN   0.953125   0.11880   7.274975    NaN    NaN
94  2747675  NaN  NaN  NaN  NaN   0.871250       NaN        NaN    NaN    NaN

[95 rows x 10 columns]

In [250]:
target_nutrient_dict

{1003: 'protein',
 1004: 'fat',
 1005: 'carbohydrate',
 1008: 'energy_kcal',
 2048: 'energy_kcal',
 203: 'protein',
 204: 'fat',
 205: 'carbohydrate',
 208: 'energy_kcal'}

In [251]:
# Rename columns
target_whole_foods_df.rename(columns=target_nutrient_dict, inplace=True)
target_whole_foods_df

,fdc_id,protein,fat,carbohydrate,energy_kcal,protein,fat,carbohydrate,energy_kcal,energy_kcal
0,324860,NaN,NaN,NaN,NaN,22.500000,51.10000,22.300000,597.0,597.0
1,325198,NaN,NaN,NaN,NaN,18.000000,30.60000,5.270000,366.0,366.0
2,325430,NaN,NaN,NaN,NaN,0.910000,0.27000,10.100000,42.0,42.0
3,327046,NaN,NaN,NaN,NaN,1.060000,0.44000,14.000000,58.0,58.0
4,327198,NaN,NaN,NaN,NaN,0.820000,0.18000,8.160000,34.0,NaN
...,...,...,...,...,...,...,...,...,...,...
90,2747665,NaN,NaN,NaN,NaN,0.656250,0.08313,4.056820,NaN,NaN
91,2747671,NaN,NaN,NaN,NaN,8.806250,0.55080,0.932150,NaN,NaN
92,2747673,NaN,NaN,NaN,NaN,24.700000,0.38750,-0.104500,NaN,NaN
93,2747674,NaN,NaN,NaN,NaN,0.953125,0.11880,7.274975,NaN,NaN
94,2747675,NaN,NaN,NaN,NaN,0.871250,NaN,NaN,NaN,NaN

In [252]:
whole_foods_id_map

{1750339: 'apple',
 1105314: 'banana',
 2263889: 'blueberries',
 2346409: 'strawberries',
 746771: 'orange',
 2710833: 'mango',
 2346398: 'pineapple',
 2747675: 'watermelon',
 2263890: 'grapes',
 746773: 'pear',
 325430: 'peach',
 327046: 'kiwi',
 2709246: 'papaya',
 2710824: 'avocado',
 2709267: 'pomegranate',
 2346399: 'cherries',
 2263888: 'raspberries',
 2727581: 'blackberries',
 327198: 'cantaloupe',
 2758977: 'grapefruit',
 2710837: 'plum',
 2710815: 'apricot',
 746768: 'figs',
 2709203: 'dates',
 2707501: 'coconut',
 746764: 'carrots',
 1750347: 'mushrooms',
 747447: 'broccoli',
 2685573: 'cauliflower',
 2346407: 'cabbage',
 1750352: 'spinach',
 2346388: 'lettuce',
 2346406: 'cucumber',
 2685578: 'tomato',
 2258588: 'bell_pepper',
 1104962: 'onion',
 1104647: 'garlic',
 2346401: 'potato',
 2346404: 'sweet_potato',
 2727578: 'pumpkin',
 2685568: 'zucchini',
 2685577: 'eggplant',
 2710823: 'asparagus',
 2346405: 'celery',
 2709853: 'green_beans',
 2644291: 'peas',
 2710826: 'corn',
 2685576: 'beetroot',
 2747665: 'radish',
 2747674: 'turnip',
 746763: 'beef',
 331897: 'chicken_wings',
 329490: 'egg',
 2759004: 'chicken_breast',
 2706027: 'chicken_thigh',
 2646168: 'pork_chop',
 749420: 'bacon',
 2514747: 'turkey_breast',
 2684440: 'salmon',
 2747673: 'tuna',
 2684443: 'shrimp',
 2684446: 'crab',
 2747657: 'lobster',
 2747671: 'squid',
 2684444: 'cod',
 2706293: 'sardines',
 2684442: 'tilapia',
 2727570: 'lamb_chop',
 2706137: 'duck_breast',
 2759002: 'ham',
 2644283: 'lentils',
 2644282: 'chickpeas',
 2707379: 'kidney_beans',
 2707359: 'black_beans',
 2515376: 'peanuts',
 2346393: 'almonds',
 2707497: 'cashews',
 2346394: 'walnuts',
 2515379: 'pistachios',
 2707585: 'sunflower_seeds',
 2515380: 'pumpkin_seeds',
 2707586: 'sesame_seeds',
 2710819: 'chia_seeds',
 2707388: 'soybeans',
 2710281: 'honey',
 746782: 'milk',
 2259793: 'yogurt',
 325198: 'cheddar_cheese',
 2647440: 'Cheese, provolone, sliced',
 790508: 'butter',
 2512381: 'rice',
 2709033: 'brown_rice',
 2346396: 'oats',
 335240: 'bread',
 2758998: 'pasta',
 2706480: 'noodles',
 2707684: 'bagel',
 2708216: 'popcorn',
 324860: 'peanut_butter'}

In [253]:
# Filter to target foods and nutrients, then map nutrient names
target_whole_foods_df = food_nutrient[
    (food_nutrient["fdc_id"].isin(list(whole_foods_id_map.keys()))) & 
    (food_nutrient["nutrient_id"].isin(list(target_nutrient_dict.keys())))
][["fdc_id", "nutrient_id", "amount"]].copy()

# Map nutrient IDs to names BEFORE pivoting
target_whole_foods_df["nutrient_name"] = target_whole_foods_df["nutrient_id"].map(target_nutrient_dict)

# Pivot by name — same names get merged into one column, taking first non-null
target_whole_foods_df = target_whole_foods_df.pivot_table(
    "amount", "fdc_id", "nutrient_name", aggfunc="first"
)

# Clean up
target_whole_foods_df = target_whole_foods_df.reset_index(drop=False).rename_axis(None, axis=1)
target_whole_foods_df

     fdc_id  carbohydrate  energy_kcal       fat    protein
0    324860     22.300000        597.0  51.10000  22.500000
1    325198      5.270000        366.0  30.60000  18.000000
2    325430     10.100000         42.0   0.27000   0.910000
3    327046     14.000000         58.0   0.44000   1.060000
4    327198      8.160000         34.0   0.18000   0.820000
..      ...           ...          ...       ...        ...
90  2747665      4.056820          NaN   0.08313   0.656250
91  2747671      0.932150          NaN   0.55080   8.806250
92  2747673     -0.104500          NaN   0.38750  24.700000
93  2747674      7.274975          NaN   0.11880   0.953125
94  2747675           NaN          NaN       NaN   0.871250

[95 rows x 5 columns]

In [254]:
# Check if a survey food ID exists in food_nutrient
food_nutrient[food_nutrient["fdc_id"] == 2710616]  # beer

,id,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acquired,nutrient_name
510549,34476297,2710616,627,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
510550,34476239,2710616,203,0.46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
510551,34476267,2710616,401,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
510552,34476292,2710616,618,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
510553,34476280,2710616,578,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
510609,34476261,2710616,322,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
510610,34476287,2710616,611,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
510611,34476249,2710616,301,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
510612,34476299,2710616,629,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
510613,34476259,2710616,320,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [255]:
# Show which foods in the map have NO nutrient data
all_ids = set(whole_foods_id_map.keys())
found_ids = set(target_whole_foods_df["fdc_id"].unique())
missing_ids = all_ids - found_ids
for mid in missing_ids:
    print(f"❌ {whole_foods_id_map[mid]:20s} (ID: {mid})")

❌ grapefruit           (ID: 2758977)
❌ ham                  (ID: 2759002)
❌ chicken_breast       (ID: 2759004)
❌ pasta                (ID: 2758998)

In [256]:
# Find which nutrient IDs exist for your missing survey foods
survey_ids_in_map = [k for k in whole_foods_id_map.keys() if str(k).startswith("27")]
survey_nutrients = food_nutrient[food_nutrient["fdc_id"].isin(survey_ids_in_map)]
print("Nutrient IDs available in survey foods:")
print(survey_nutrients["nutrient_id"].unique())

Nutrient IDs available in survey foods:
[1063 2048 2047 1005 1003 1162 1079 1101 1014 1092 1004 1098 1095 1093
 1012 1090 1013 1010 1007 1002 1089 1011 1091 1176 1051 1087 1009 1175
 1165 1167 1177 1166 1253 1178 1103 2020 2018 2016 1329 2014 1273 1312
 2004 1305 1263 1303 1271 1333 1259 1335 1293 1267 1257 1311 1405 2024
 1262 1334 1277 1414 1260 1406 2006 1274 2005 1266 1270 1281 1321 1299
 1301 2013 2025 1265 2019 1276 1275 1411 2021 2026 1258 2008 1300 2003
 1264 1292 2015 2023 2007 2017 1261 1304 1180 1268 1323 1269  630  204
  312  338  301  263  208  406  618  328  203  631  432  645  621  307
  269  626  221  205  627  617  405  430  619  309  303  322  319  573
  417  629  323  334  601  317  337  609  262  613  418  255  612  578
  431  610  608  611  646  607  404  304  614  606  306  620  415  435
  421  321  401  291  320  628  305]

In [257]:
# Add food names
target_whole_foods_df["food_name"] = target_whole_foods_df["fdc_id"].map(whole_foods_id_map)
target_whole_foods_df

     fdc_id  carbohydrate  energy_kcal       fat    protein       food_name
0    324860     22.300000        597.0  51.10000  22.500000   peanut_butter
1    325198      5.270000        366.0  30.60000  18.000000  cheddar_cheese
2    325430     10.100000         42.0   0.27000   0.910000           peach
3    327046     14.000000         58.0   0.44000   1.060000            kiwi
4    327198      8.160000         34.0   0.18000   0.820000      cantaloupe
..      ...           ...          ...       ...        ...             ...
90  2747665      4.056820          NaN   0.08313   0.656250          radish
91  2747671      0.932150          NaN   0.55080   8.806250           squid
92  2747673     -0.104500          NaN   0.38750  24.700000            tuna
93  2747674      7.274975          NaN   0.11880   0.953125          turnip
94  2747675           NaN          NaN       NaN   0.871250      watermelon

[95 rows x 6 columns]

All amounts are per 100g.

In [260]:
# Show all foods with any NaN
nan_foods = target_whole_foods_df[target_whole_foods_df.isna().any(axis=1)]
nan_foods[["food_name", "protein", "fat", "carbohydrate", "energy_kcal"]]

       food_name   protein   fat  carbohydrate  energy_kcal
16        butter       NaN  82.2           NaN     739.8000
87       pumpkin  0.854375   NaN           NaN       3.4175
88  blackberries  1.526250   NaN           NaN       6.1050
94    watermelon  0.871250   NaN           NaN       3.4850

In [259]:
# Calculate missing energy_kcal using: 4*protein + 4*carbs + 9*fat
mask = target_whole_foods_df["energy_kcal"].isna()
target_whole_foods_df.loc[mask, "energy_kcal"] = (
    4 * target_whole_foods_df.loc[mask, "protein"].fillna(0) +
    4 * target_whole_foods_df.loc[mask, "carbohydrate"].fillna(0) +
    9 * target_whole_foods_df.loc[mask, "fat"].fillna(0)
)

# Show which foods were fixed
fixed = target_whole_foods_df.loc[mask, ["food_name", "energy_kcal"]]
if len(fixed) > 0:
    print(f"✅ Fixed {len(fixed)} foods with calculated energy_kcal:")
    for _, row in fixed.iterrows():
        print(f"   {row['food_name']:20s} → {row['energy_kcal']:.1f} kcal")
else:
    print("✅ No missing energy values to fix!")

✅ Fixed 9 foods with calculated energy_kcal:
   butter               → 739.8 kcal
   pumpkin              → 3.4 kcal
   blackberries         → 6.1 kcal
   lobster              → 58.8 kcal
   radish               → 19.6 kcal
   squid                → 43.9 kcal
   tuna                 → 101.9 kcal
   turnip               → 34.0 kcal
   watermelon           → 3.5 kcal

## Export first 10 target food nutrition information

In [261]:
target_whole_foods_df.to_csv("target_hundred_whole_food_nutrition_info.csv", index=False)

In [180]:
ten_whole_foods

['chicken_wings',
 'apple',
 'banana',
 'beef',
 'carrots',
 'egg',
 'strawberries',
 'blueberries',
 'mushrooms',
 'honey']

In [181]:
foundation_food.head(-10)

,fdc_id,data_type,description,food_category_id,publication_date
651,321358,foundation_food,"hummus, commercial",16.0,2019-04-01
652,321359,foundation_food,"milk, reduced fat, fluid, 2% milkfat, with add...",1.0,2019-04-01
653,321360,foundation_food,"tomatoes, grape, raw",11.0,2019-04-01
798,321505,foundation_food,"salt, table, iodized",2.0,2019-04-01
904,321611,foundation_food,"beans, snap, green, canned, regular pack, drai...",11.0,2019-04-01
...,...,...,...,...,...
93407,2710800,survey_fndds_food,"cabbage, cooked, as ingredient",9999.0,2022-10-28
93408,2710801,survey_fndds_food,"cauliflower, cooked, as ingredient",9999.0,2022-10-28
93409,2710802,survey_fndds_food,"eggplant, cooked, as ingredient",9999.0,2022-10-28
93410,2710803,survey_fndds_food,"green beans, cooked, as ingredient",9999.0,2022-10-28
93411,2710804,survey_fndds_food,"summer squash, cooked, as ingredient",9999.0,2022-10-28

# Mine

In [52]:
foundation_food["data_type"].unique()

<ArrowStringArray>
['foundation_food', 'survey_fndds_food']
Length: 2, dtype: str

In [53]:
foundation_food["description"].unique()

<ArrowStringArray>
[                                                        'hummus, commercial',
   'milk, reduced fat, fluid, 2% milkfat, with added vitamin a and vitamin d',
                                                       'tomatoes, grape, raw',
                                                       'salt, table, iodized',
                   'beans, snap, green, canned, regular pack, drained solids',
                                                              'broccoli, raw',
        'milk, lowfat, fluid, 1% milkfat, with added vitamin a and vitamin d',
 'milk, nonfat, fluid, with added vitamin a and vitamin d (fat free or skim)',
                           'milk, whole, 3.25% milkfat, with added vitamin d',
                                                'frankfurter, beef, unheated',
 ...
                                         'cauliflower, cooked, as ingredient',
                                            'eggplant, cooked, as ingredient',
                                         'green beans, cooked, as ingredient',
                                       'summer squash, cooked, as ingredient',
                              'dark green vegetables as ingredient in omelet',
                                           'tomatoes as ingredient in omelet',
                                   'other vegetables as ingredient in omelet',
                                          'vegetables as ingredient in curry',
                                          'sauce as ingredient in hamburgers',
                                       'industrial oil as ingredient in food']
Length: 7221, dtype: str

In [54]:
foundation_foods[50:100]

10162    turkey, ground, 93% lean, 7% fat, pan-broiled ...
11190    chicken, broilers or fryers, drumstick, meat o...
11253    chicken, broiler or fryers, breast, skinless, ...
11575     sauce, pasta, spaghetti/marinara, ready-to-serve
11690    ham, sliced, pre-packaged, deli meat (96%fat f...
11890    pears, raw, bartlett (includes foods for usda'...
12084     olives, green, manzanilla, stuffed with pimiento
12157    sausage, pork, chorizo, link or ground, cooked...
12301                 cookies, oatmeal, soft, with raisins
12574                   tomatoes, canned, red, ripe, diced
12667                                   fish, haddock, raw
12769                                   fish, pollock, raw
13487    fish, tuna, light, canned in water, drained so...
13540                                   sugars, granulated
13755             restaurant, chinese, sweet and sour pork
13829        restaurant, chinese, fried rice, without meat
13921                     restaurant, latino, tamale, pork
14013    restaurant, latino, pupusas con frijoles (pupu...
14142    beef, loin, top loin steak, boneless, lip-on, ...
14190    beef, loin, tenderloin roast, separable lean o...
14191    beef, round, eye of round roast, boneless, sep...
14256    beef, round, top round roast, boneless, separa...
14354    beef, short loin, t-bone steak, bone-in, separ...
14402    beef, short loin, porterhouse steak, separable...
14533            bread, whole-wheat, commercially prepared
14538            beans, dry, dark red kidney (0% moisture)
14599                       beans, dry, pink (0% moisture)
14712                       beans, dry, navy (0% moisture)
14715           beans, dry, light red kidney (0% moisture)
14718                      beans, dry, brown (0% moisture)
14721               beans, dry, flor de mayo (0% moisture)
14726                    beans, dry, carioca (0% moisture)
14735                        beans, dry, tan (0% moisture)
14988                      beans, dry, pinto (0% moisture)
15067                  beans, dry, small red (0% moisture)
15070                 beans, dry, medium red (0% moisture)
15075                  beans, dry, cranberry (0% moisture)
15078                  beans, dry, light tan (0% moisture)
15205                      beans, dry, black (0% moisture)
15220                beans, dry, small white (0% moisture)
15223                        beans, dry, red (0% moisture)
15360             beans, dry, great northern (0% moisture)
15361    beef, loin, tenderloin roast, separable lean o...
15362    beef, loin, top loin steak, boneless, lip-on, ...
15363    beef, round, eye of round roast, boneless, sep...
15364    beef, round, top round roast, boneless, separa...
15365    beef, short loin, porterhouse steak, separable...
15366    beef, short loin, t-bone steak, bone-in, separ...
15367                          carrots, frozen, unprepared
15368                        cheese, dry white, queso seco
Name: description, dtype: str

In [55]:
for food in foundation_foods:
    if "chicken" in food.lower():
        print(food)

chicken, broilers or fryers, drumstick, meat only, cooked, braised
chicken, broiler or fryers, breast, skinless, boneless, meat only, cooked, braised
mock chicken legs, cooked
chicken, ns as to part and cooking method, ns as to skin eaten
chicken, ns as to part and cooking method, skin eaten
chicken, ns as to part and cooking method, skin not eaten
chicken, ns as to part, baked, broiled, or roasted, ns as to skin eaten
chicken, ns as to part, baked, broiled, or roasted, skin eaten
chicken, ns as to part, baked, broiled, or roasted, skin not eaten
chicken, ns as to part, rotisserie, ns as to skin eaten
chicken, ns as to part, rotisserie, skin eaten
chicken, ns as to part, rotisserie, skin not eaten
chicken, ns as to part, stewed, ns as to skin eaten
chicken, ns as to part, stewed, skin eaten
chicken, ns as to part, stewed, skin not eaten
chicken, ns as to part, grilled without sauce, ns as to skin eaten
chicken, ns as to part, grilled without sauce, skin eaten
chicken, ns as to part, grilled without sauce, skin not eaten
chicken, ns as to part, grilled with sauce, ns as to skin eaten
chicken, ns as to part, grilled with sauce, skin eaten
chicken, ns as to part, grilled with sauce, skin not eaten
chicken, ns as to part, sauteed, skin eaten
chicken, ns as to part, sauteed, skin not eaten
chicken, ns as to part, fried, coated, skin / coating eaten
chicken, ns as to part, fried, coated, skin / coating not eaten
chicken, ns as to part, baked, coated, skin / coating eaten
chicken, ns as to part, baked, coated, skin / coating not eaten
chicken breast, ns as to cooking method, skin eaten
chicken breast, ns as to cooking method, skin not eaten
chicken breast, baked, broiled, or roasted, skin eaten, from raw
chicken breast, baked, broiled, or roasted, skin not eaten, from raw
chicken breast, baked or broiled, skin eaten, from pre-cooked
chicken breast, baked or broiled, skin not eaten, from pre-cooked
chicken breast, baked or broiled, skin eaten, from fast food / restaurant
chicken breast, baked or broiled, skin not eaten, from fast food / restaurant
chicken breast, baked, broiled, or roasted with marinade, skin eaten, from raw
chicken breast, baked, broiled, or roasted with marinade, skin not eaten, from raw
chicken breast, rotisserie, skin eaten
chicken breast, rotisserie, skin not eaten
chicken breast, stewed, skin eaten
chicken breast, stewed, skin not eaten
chicken breast, grilled without sauce, skin eaten
chicken breast, grilled without sauce, skin not eaten
chicken breast, grilled with sauce, skin eaten
chicken breast, grilled with sauce, skin not eaten
chicken breast, sauteed, skin eaten
chicken breast, sauteed, skin not eaten
chicken breast, fried, coated, skin / coating eaten, from raw
chicken breast, fried, coated, skin / coating not eaten, from raw
chicken breast, fried, coated, prepared skinless, coating eaten, from raw
chicken breast, fried, coated, skin / coating eaten, from pre-cooked
chicken breast, fried, coated, skin / coating not eaten, from pre-cooked
chicken breast, fried, coated, skin / coating eaten, from fast food / restaurant
chicken breast, fried, coated, skin / coating not eaten, from fast food / restaurant
chicken breast, baked, coated, skin / coating eaten
chicken breast, baked, coated, skin / coating not eaten
chicken leg, drumstick and thigh, ns as to cooking method, skin eaten
chicken leg, drumstick and thigh, ns as to cooking method, skin not eaten
chicken leg, drumstick and thigh, baked or broiled, skin eaten
chicken leg, drumstick and thigh, baked or broiled, skin not eaten
chicken leg, drumstick and thigh, rotisserie, skin eaten
chicken leg, drumstick and thigh, rotisserie, skin not eaten
chicken leg, drumstick and thigh, stewed, skin eaten
chicken leg, drumstick and thigh, stewed, skin not eaten
chicken leg, drumstick and thigh, grilled without sauce, skin eaten
chicken leg, drumstick and thigh, grilled without sauce, skin not eaten
chicken leg, drumstick and thigh, grilled with sauce, skin eaten
chicken leg, drumstick and thigh, grilled with sauce, skin not eaten
chicken leg, drumstick and thigh, sauteed, skin eaten
chicken leg, drumstick and thigh, sauteed, skin not eaten
chicken leg, drumstick and thigh, fried, coated, skin / coating eaten
chicken leg, drumstick and thigh, fried, coated, skin / coating not eaten
chicken leg, drumstick and thigh, baked, coated, skin / coating eaten
chicken leg, drumstick and thigh, baked, coated, skin / coating not eaten
chicken drumstick, ns as to cooking method, skin eaten
chicken drumstick, ns as to cooking method, skin not eaten
chicken drumstick, baked, broiled, or roasted, skin eaten, from raw
chicken drumstick, baked, broiled, or roasted, skin not eaten, from raw
chicken drumstick, baked or broiled, skin eaten, from pre-cooked
chicken drumstick, baked or broiled, skin not eaten, from pre-cooked
chicken drumstick, baked or broiled, skin eaten, from fast food / restaurant
chicken drumstick, baked or broiled, skin not eaten, from fast food / restaurant
chicken drumstick, rotisserie, skin eaten
chicken drumstick, rotisserie, skin not eaten
chicken drumstick, grilled without sauce, skin eaten
chicken drumstick, grilled without sauce, skin not eaten
chicken drumstick, grilled with sauce, skin eaten
chicken drumstick, grilled with sauce, skin not eaten
chicken drumstick, stewed, skin eaten
chicken drumstick, stewed, skin not eaten
chicken drumstick, sauteed, skin eaten
chicken drumstick, sauteed, skin not eaten
chicken drumstick, fried, coated, skin / coating eaten, from raw
chicken drumstick, fried, coated, skin / coating not eaten, from raw
chicken drumstick, fried, coated, prepared skinless, coating eaten, from raw
chicken drumstick, fried, coated, skin / coating eaten, from pre-cooked
chicken drumstick, fried, coated, skin / coating not eaten, from pre-cooked
chicken drumstick, fried, coated, skin / coating eaten, from fast food / restaurant
chicken drumstick, fried, coated, skin / coating not eaten, from fast food / restaurant
chicken drumstick, baked, coated, skin / coating eaten
chicken drumstick, baked, coated, skin / coating not eaten
chicken thigh, ns as to cooking method, skin eaten
chicken thigh, ns as to cooking method, skin not eaten
chicken thigh, baked, broiled, or roasted, skin eaten, from raw
chicken thigh, baked, broiled, or roasted, skin not eaten, from raw
chicken thigh, baked or broiled, skin eaten, from pre-cooked
chicken thigh, baked or broiled, skin not eaten, from pre-cooked
chicken thigh, baked or broiled, skin eaten, from fast food / restaurant
chicken thigh, baked or broiled, skin not eaten, from fast food / restaurant
chicken thigh, rotisserie, skin eaten
chicken thigh, rotisserie, skin not eaten
chicken thigh, stewed, skin eaten
chicken thigh, stewed, skin not eaten
chicken thigh, grilled without sauce, skin eaten
chicken thigh, grilled without sauce, skin not eaten
chicken thigh, grilled with sauce, skin eaten
chicken thigh, grilled with sauce, skin not eaten
chicken thigh, sauteed, skin eaten
chicken thigh, sauteed, skin not eaten
chicken thigh, fried, coated, skin / coating eaten, from raw
chicken thigh, fried, coated, skin / coating not eaten, from raw
chicken thigh, fried, coated, prepared skinless, coating eaten, from raw
chicken thigh, fried, coated, skin / coating eaten, from pre-cooked
chicken thigh, fried, coated, skin / coating not eaten, from pre-cooked
chicken thigh, fried, coated, skin / coating eaten, from fast food
chicken thigh, fried, coated, skin / coating not eaten, from fast food
chicken thigh, fried, coated, skin / coating eaten, from restaurant
chicken thigh, fried, coated, skin / coating not eaten, from restaurant
chicken thigh, baked, coated, skin / coating eaten
chicken thigh, baked, coated, skin / coating not eaten
chicken wing, ns as to cooking method
chicken wing, baked, broiled, or roasted, from raw
chicken wing, baked or broiled, from pre-cooked
chicken wing, baked or broiled, from fast food / restaurant
chicken wing, rotisserie
chicken wing, stewed
chicken wing, grilled without sauce
chicken wing, grilled with sauce
chicken wing, sauteed
chicken wing, fried, coated, from raw
chicken wing, fried, coated, from pre-cooked
chicken wing, fried, coated, from fast food
chicken wing, fried, coated, from restaurant
chicken wing, baked, coated
chicken "wings" with hot sauce, from fast food / restaurant
chicken "wings" with other sauces or seasoning, from fast food / restaurant
chicken "wings", plain, from fast food / restaurant
chicken "wings" with hot sauce, from precooked
chicken "wings" with other sauces or seasoning, from precooked
chicken "wings", plain, from precooked
chicken "wings" with hot sauce, from other sources
chicken "wings" with other sauces or seasoning, from other sources
chicken "wings", plain, from other sources
chicken "wings", boneless, with hot sauce, from fast food / restaurant
chicken "wings", boneless, with hot sauce, from other sources
chicken, back
chicken, neck or ribs
chicken, tail
chicken skin
chicken feet
chicken, canned, meat only
chicken, chicken roll, roasted
chicken patty, breaded
chicken fillet, breaded
chicken fillet, grilled
chicken, ground
chicken nuggets, nfs
chicken nuggets, from fast food
chicken nuggets, from restaurant
chicken nuggets, from school lunch
chicken nuggets, from frozen
chicken nuggets, from other sources
chicken tenders or strips, nfs
chicken tenders or strips, breaded, from fast food
chicken tenders or strips, breaded, from restaurant
chicken tenders or strips, breaded, from school lunch
chicken tenders or strips, breaded, from frozen
chicken tenders or strips, breaded, from other sources
fried chicken chunks, puerto rican style
chicken, baby food, ns as to strained or junior
chicken, baby food, strained
chicken, baby food, junior
chicken stick, baby food
chicken liver, braised
chicken liver, fried
liver paste or pate, chicken
frankfurter or hot dog, chicken
turkey or chicken and beef sausage
turkey or chicken sausage
turkey or chicken sausage, reduced sodium
turkey or chicken sausage, reduced fat
turkey or chicken and pork sausage
turkey or chicken, pork, and beef sausage, reduced sodium
chicken, prepackaged or deli, luncheon meat
chicken, prepackaged or deli, luncheon meat, reduced sodium
ham, pork and chicken, canned luncheon meat, chopped, minced, pressed, spiced, reduced fat and reduced sodium
ham, pork, and chicken, canned luncheon meat, chopped, minced, pressed, spiced, reduced sodium
chicken salad spread
chicken or turkey cacciatore
stewed chicken with tomato-based sauce, mexican style
chili con carne with chicken or turkey and beans
chicken with gravy
chicken or turkey fricassee
chicken or turkey with cream sauce
chicken or turkey with mushroom sauce
chicken or turkey with teriyaki
chicken, shredded or pulled, with barbecue sauce
sweet and sour chicken or turkey
sweet and sour chicken or turkey, without vegetables
chicken curry
chicken curry with rice
chicken with mole sauce
chicken or turkey with cheese sauce
chicken or turkey cordon bleu
chicken or turkey parmigiana
orange chicken
sesame chicken
chicken kiev
stuffed chicken, drumstick or breast, puerto rican style
chicken or turkey hash
chicken or turkey and potatoes with gravy
chicken or turkey and noodles, no sauce
chicken or turkey and noodles with gravy
chicken or turkey and noodles with mushroom sauce
chicken or turkey and noodles with cream or white sauce
chicken or turkey and noodles with cheese sauce
chicken or turkey tetrazzini
chicken or turkey and noodles with tomato-based sauce
chicken or turkey and noodles with soy-based sauce
chicken or turkey and rice, no sauce
biryani with chicken
chicken or turkey and rice with cream sauce
chicken or turkey and rice with mushroom sauce
chicken or turkey and rice with tomato-based sauce
chicken or turkey and rice with soy-based sauce
chicken or turkey with dumplings
chicken or turkey with stuffing
chicken or turkey cake, patty, or croquette
chicken or turkey souffle
meat loaf made with chicken or turkey
meat loaf made with chicken or turkey, with tomato-based sauce
chicken or turkey, potatoes, corn, and cheese, with gravy
chicken or turkey, potatoes, and vegetables including carrots, broccoli, and/or dark-green leafy; no sauce
chicken or turkey, potatoes, and vegetables excluding carrots, broccoli, and dark-green leafy; no sauce
chicken or turkey, potatoes, and vegetables including carrots, broccoli, and/or dark-green leafy; gravy
chicken or turkey, potatoes, and vegetables excluding carrots, broccoli, and dark-green leafy; gravy
chicken or turkey, potatoes, and vegetables including carrots, broccoli, and/or dark-green leafy; cream sauce, white sauce, or mushroom sauce
chicken or turkey, potatoes, and vegetables excluding carrots, broccoli, and dark-green leafy; cream sauce, white sauce, or mushroom sauce
chicken or turkey, potatoes, and vegetables including carrots, broccoli, and/or dark-green leafy; cheese sauce
chicken or turkey, potatoes, and vegetables excluding carrots, broccoli, and dark-green leafy; cheese sauce
chicken or turkey, potatoes, and vegetables including carrots, broccoli, and/or dark-green leafy; tomato-based sauce
chicken or turkey, potatoes, and vegetables excluding carrots, broccoli, and dark-green leafy; tomato-based sauce
chicken or turkey stew with potatoes and vegetables including carrots, broccoli, and/or dark-green leafy; gravy
chicken or turkey stew with potatoes and vegetables excluding carrots, broccoli, and dark-green leafy; gravy
chicken or turkey stew with potatoes and vegetables including carrots, broccoli, and/or dark-green leafy; tomato-based sauce
chicken or turkey stew with potatoes and vegetables excluding carrots, broccoli, and dark-green leafy; tomato- based sauce
chicken or turkey, noodles, and vegetables including carrots, broccoli, and/or dark-green leafy; no sauce
chicken or turkey, noodles, and vegetables excluding carrots, broccoli, and dark-green leafy; no sauce
chicken or turkey, noodles, and vegetables including carrots, broccoli, and/or dark-green leafy; gravy
chicken or turkey, noodles, and vegetables excluding carrots, broccoli, and dark-green leafy; gravy
chicken or turkey, noodles, and vegetables including carrots, broccoli, and/or dark-green leafy; cream sauce, white sauce, or mushroom sauce
chicken or turkey, noodles, and vegetables excluding carrots, broccoli, and/or dark-green leafy; cream sauce, white sauce, or mushroom sauce
chicken or turkey, noodles, and vegetables including carrots, broccoli, and/or dark-green leafy; tomato-based sauce
chicken or turkey, noodles, and vegetables excluding carrots, broccoli, and dark-green leafy; tomato-based sauce
chicken or turkey chow mein or chop suey with noodles
chicken or turkey, noodles, and vegetables including carrots, broccoli, and/or dark-green leafy; cheese sauce
chicken or turkey, noodles, and vegetables excluding carrots, broccoli, and dark-green leafy; cheese sauce
chicken or turkey, rice, and vegetables including carrots, broccoli, and/or dark-green leafy; no sauce
chicken or turkey, rice, and vegetables excluding carrots, broccoli, and dark-green leafy; no sauce
chicken or turkey, rice, and vegetables including carrots, broccoli, and/or dark-green leafy; gravy
chicken or turkey, rice, and vegetables excluding carrots, broccoli, and dark-green leafy; gravy
chicken or turkey, rice, corn, and cheese, with gravy
chicken or turkey, rice, and vegetables including carrots, broccoli, and/or dark-green leafy; soy-based sauce
chicken or turkey, rice, and vegetables excluding carrots, broccoli, and dark-green leafy; soy-based sauce
chicken or turkey, rice, and vegetables including carrots, broccoli, and/or dark-green leafy; cream sauce, white sauce, or mushroom sauce
chicken or turkey, rice, and vegetables excluding carrots, broccoli, and dark-green leafy; cream sauce, white sauce, or mushroom sauce
chicken or turkey, rice, and vegetables including carrots, broccoli, and/or dark-green leafy; cheese sauce
chicken or turkey, rice, and vegetables excluding carrots, broccoli, and dark-green leafy; cheese sauce
chicken or turkey, rice, and vegetables including carrots, broccoli, and/or dark-green leafy; tomato-based sauce
chicken or turkey, rice, and vegetables excluding carrots, broccoli, and dark-green leafy; tomato-based sauce
chicken or turkey pot pie
chicken or turkey, stuffing, and vegetables including carrots, broccoli, and/or dark-green leafy; no sauce
chicken or turkey,stuffing, and vegetables excluding carrots, broccoli, and dark green leafy; no sauce
chicken or turkey, stuffing, and vegetables including carrots, broccoli, and/or dark-green leafy; gravy
chicken or turkey, stuffing, and vegetables excluding carrots, broccoli, and dark-green leafy; gravy
chicken or turkey, dumplings, and vegetables including carrots, broccoli, and/or dark green leafy; gravy
chicken or turkey, dumplings, and vegetables excluding carrots, broccoli, and dark green leafy; gravy
chicken fricassee, puerto rican style
chicken or turkey and vegetables including carrots, broccoli, and/or dark-green leafy; no potatoes, no sauce
chicken or turkey and vegetables excluding carrots, broccoli, and dark-green leafy; no potatoes, no sauce
chicken or turkey shish kabob with vegetables, excluding potatoes
chicken or turkey creole, without rice
chicken or turkey and vegetables including carrots, broccoli, and/or dark-green leafy; no potatoes, gravy
chicken or turkey and vegetables excluding carrots, broccoli, and dark-green leafy; no potatoes, gravy
chicken or turkey a la king with vegetables including carrots, broccoli, and/or dark-green leafy; no potatoes, cream, white, or soup-based sauce
chicken or turkey a la king with vegetables excluding carrorts, broccoli, and dark-green leafy; no potatoes, cream, white, or soup-based sauce
chicken or turkey divan
chicken or turkey and vegetables including carrots, broccoli, and/or dark-green leafy; no potatoes, soy-based sauce
chicken or turkey and vegetables excluding carrots, broccoli, and dark-green leafy; no potatoes, soy-based sauce
chicken or turkey and vegetables including carrots, broccoli, and/or dark-green leafy; no potatoes, tomato-based sauce
chicken or turkey and vegetables excluding carrots, broccoli, and dark-green leafy; no potatoes, tomato-based sauce
general tso chicken
kung pao chicken
almond chicken
chicken or turkey chow mein or chop suey, no noodles
chicken or turkey salad, made with mayonnaise
chicken or turkey salad with nuts and/or fruits
chicken or turkey salad with egg
chicken or turkey salad, made with light mayonnaise
chicken or turkey salad, made with mayonnaise-type salad dressing
chicken or turkey salad, made with light mayonnaise-type salad dressing
chicken or turkey salad, made with creamy dressing
chicken or turkey salad, made with light creamy dressing
chicken or turkey salad, made with italian dressing
chicken or turkey salad, made with light italian dressing
chicken or turkey salad, made with any type of fat free dressing
chicken or turkey garden salad, chicken and/or turkey, tomato and/or carrots, other vegetables, no dressing
chicken or turkey garden salad, chicken and/or turkey, other vegetables excluding tomato and carrots, no dressing
chicken or turkey garden salad with bacon and cheese, chicken and/or turkey, bacon, cheese, lettuce and/or greens, tomato and/or carrots, other vegetables, no dressing
chicken or turkey, breaded, fried, garden salad with bacon and cheese, chicken and/or turkey, bacon, cheese, lettuce and/or greens, tomato and/or carrots, other vegetables, no dressing
chicken or turkey garden salad with cheese, chicken and/or turkey, cheese, lettuce and/or greens, tomato and/or carrots, other vegetables, no dressing
chicken or turkey, breaded, fried, garden salad with cheese, chicken and/or turkey, cheese, lettuce and/or greens, tomato and/or carrots, other vegetables, no dressing

In [56]:
foundation_food[foundation_food["description"].str.contains("chicken", case=False)]

,fdc_id,data_type,description,food_category_id,publication_date
11190,331897,foundation_food,"chicken, broilers or fryers, drumstick, meat o...",5.0,2019-04-01
11253,331960,foundation_food,"chicken, broiler or fryers, breast, skinless, ...",5.0,2019-04-01
28471,1098388,survey_fndds_food,"mock chicken legs, cooked",NaN,2020-10-30
28501,1098418,survey_fndds_food,"chicken, ns as to part and cooking method, ns ...",NaN,2020-10-30
28502,1098419,survey_fndds_food,"chicken, ns as to part and cooking method, ski...",NaN,2020-10-30
...,...,...,...,...,...
33874,1103791,survey_fndds_food,"vegetable and chicken, baby food, ns as to str...",NaN,2020-10-30
33875,1103792,survey_fndds_food,"vegetable and chicken, baby food, strained",NaN,2020-10-30
33876,1103793,survey_fndds_food,"vegetable and chicken, baby food, junior",NaN,2020-10-30
33883,1103800,survey_fndds_food,"potato chicken pie, puerto rican style",NaN,2020-10-30
34000,1103917,survey_fndds_food,"chicken, for use with vegetables",NaN,2020-10-30

In [57]:
nutrient[nutrient["name"].str.contains("protein", case=False) | \
         nutrient["name"].str.contains("carbohydrate", case=False) | \
         nutrient["name"].str.contains("fat", case=False)]["name"].unique()

<ArrowStringArray>
[                                                             'Protein',
                                                    'Total lipid (fat)',
                                          'Carbohydrate, by difference',
                                                      'Solids, non-fat',
                                           'Carbohydrate, by summation',
                                                     'Adjusted Protein',
                                                  'Carbohydrate, other',
                                                     'Total fat (NLEA)',
                                             'Fatty acids, total trans',
                                         'Fatty acids, total saturated',
 'Fatty acids, other than 607-615, 617-621, 624-632, 652-654, 686-689)',
                                   'Fatty acids, total monounsaturated',
                                   'Fatty acids, total polyunsaturated',
                                        'Fatty acids, saturated, other',
                                       'Fatty acids, monounsat., other',
                                       'Fatty acids, polyunsat., other',
                                        'Fatty acids, total sat., NLEA',
                                  'Fatty acids, total monounsat., NLEA',
                                  'Fatty acids, total polyunsat., NLEA',
                                   'Fatty acids, total trans-monoenoic',
                                     'Fatty acids, total trans-dienoic',
                                   'Fatty acids, total trans-polyenoic',
                                                        'Carbohydrates']
Length: 23, dtype: str

Getting IDs of Carbohydrate, Fat and Protein

* Carbohydrate, by difference = total carbohydrate

In [58]:
target_nutrients = nutrient[nutrient["name"].isin(["Protein", "Carbohydrate, by difference", "Total lipid (fat)"])]
target_nutrients

     id                         name unit_name  nutrient_nbr    rank
2  1003                      Protein         G         203.0   600.0
3  1004            Total lipid (fat)         G         204.0   800.0
4  1005  Carbohydrate, by difference         G         205.0  1110.0

In [59]:
food_nutrient[(food_nutrient["fdc_id"] ==  chicken_wing_id) & (food_nutrient["nutrient_id"].isin(list(target_nutrient_dict.keys())))]

,id,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acqured,sf.footnote,min_year_acquired,nutrient_name
41686,2259098,331897,1004,5.95,6.0,1.0,5.54,6.33,5.93,NaN,2010.0,NaN,NaN,total lipid (fat)
41718,2259079,331897,1003,23.90,NaN,49.0,23.00,24.60,24.10,NaN,NaN,NaN,NaN,protein
41729,2259099,331897,1005,0.00,NaN,49.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"carbohydrate, by difference"

Getting Target Nutrient(protein, total lipid(fat), carbohydrate, by difference) of `chicken_wing_id`

In [74]:
food_nutrient[(food_nutrient["fdc_id"] == chicken_wing_id) & food_nutrient["nutrient_id"].isin(list(target_nutrient_dict.keys()))]

,id,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acqured,sf.footnote,min_year_acquired,nutrient_name
41686,2259098,331897,1004,5.95,6.0,1.0,5.54,6.33,5.93,NaN,2010.0,NaN,NaN,total lipid (fat)
41718,2259079,331897,1003,23.90,NaN,49.0,23.00,24.60,24.10,NaN,NaN,NaN,NaN,protein
41729,2259099,331897,1005,0.00,NaN,49.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"carbohydrate, by difference"

In [95]:
food[(food["description"].str.contains("blueberry", case=False))]["description"]

31153    pie, berry, not blackberry, blueberry, boysenb...
31154    pie, berry, not blackberry, blueberry, boysenb...
31155    pie, berry, not blackberry, blueberry, boysenb...
31156                            pie, blueberry, two crust
31157              pie, blueberry, individual size or tart
31239                                     crisp, blueberry
31848           cereal (malt-o-meal blueberry muffin tops)
31888               cereal (kellogg's special k blueberry)
32788                                blueberry pie filling
32833                                      blueberry juice
32939        blueberry yogurt dessert, baby food, strained
34033                                      blueberry syrup
Name: description, dtype: str

In [100]:
# food_nutrient[(food_nutrient["fdc_id"] == chicken_curry_id) & food_nutrient["nutrient_id"].isin(list(target_nutrient_dict.keys()))]
chicken_curry_id = int(foundation_food.loc[foundation_food["description"].str.contains(pattern, case=False)].iloc[0]["fdc_id"])
chicken_curry_id

323121

**Code Snip!!!**

Setting Food Id \
`chicken_wing_id = int(foundation_food.loc[foundation_food["description"].str.contains("Chicken", case=False)].iloc[0]["fdc_id"])`

Getting Nutrition Data from ID \
`food_nutrient[(food_nutrient["fdc_id"] == chicken_wing_id) & food_nutrient["nutrient_id"].isin(list(target_nutrient_dict.keys()))]`

In [82]:
chicken_curry_id = int(foundation_food.loc[foundation_food["description"].str.contains("chicken curry", case=False)].iloc[0]["fdc_id"])
food_nutrient[(food_nutrient["fdc_id"] == chicken_curry_id) & food_nutrient["nutrient_id"].isin(list(target_nutrient_dict.keys()))]

,id,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acqured,sf.footnote,min_year_acquired,nutrient_name
218537,12988060,1099246,1005,6.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"carbohydrate, by difference"
218540,12988058,1099246,1003,6.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,protein
218555,12988059,1099246,1004,6.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,total lipid (fat)

In [172]:
# Check if 2048 nutrient entries exist for our target foods
fdc_ids_with_2048 = food_nutrient[
    (food_nutrient["fdc_id"].isin(list(whole_foods_id_map.keys()))) &
    (food_nutrient["nutrient_id"] == 2048)
]
print(f"Foods with Energy (Atwater Specific Factors) recorded: {len(fdc_ids_with_2048)}")
fdc_ids_with_2048[["fdc_id", "amount"]].merge(
    pd.DataFrame(whole_foods_id_map.items(), columns=["fdc_id", "food_name"]),
    on="fdc_id",
    how="right"
)

Foods with Energy (Atwater Specific Factors) recorded: 2

    fdc_id     amount      food_name
0  1750339  55.622745          apple
1  1105314        NaN         banana
2  1102702        NaN    blueberries
3   746763        NaN           beef
4   746764        NaN        carrots
5   331897        NaN  chicken_wings
6   329490        NaN            egg
7  1103956        NaN          honey
8  1750347  24.873258      mushrooms
9   747448        NaN   strawberries